package com.ecommerce.catalog

import com.ecommerce.platform.common.CommerceId
import com.ecommerce.platform.error.ApiException
import com.ecommerce.platform.error.ErrorCode
import com.ecommerce.platform.service.ServiceOutboxRecord
import com.ecommerce.platform.service.ServiceOutboxStore
import com.ecommerce.platform.service.newOutboxId
import kotlinx.serialization.json.Json
import java.sql.Connection
import java.sql.ResultSet
import java.sql.SQLException
import java.sql.Timestamp
import java.time.Instant
import javax.sql.DataSource

data class ProductInput(val sellerId: String, val ownerType: OwnerType, val brandId: String?, val categoryId: String, val name: String, val slug: String, val description: String, val shortDescription: String?, val skuReference: String?, val status: ProductStatus, val taxCategory: String?, val attributes: Map<String, String>, val seoTitle: String?, val seoDescription: String?, val canonicalUrl: String?, val variants: List<VariantInput>, val media: List<MediaInput>)
data class VariantInput(val sku: String, val barcode: String?, val attributes: Map<String, String>, val priceReference: String?, val weightGrams: Int?, val dimensions: Map<String, String>, val status: VariantStatus)
data class MediaInput(val mediaId: String, val mediaType: String, val url: String?, val sortOrder: Int, val altText: String?)

class CatalogRepository(private val dataSource: DataSource) : CatalogStore, ServiceOutboxStore {
    private val json = Json { encodeDefaults = true; ignoreUnknownKeys = true }

    override fun list(cursor: String?, limit: Int, categoryId: String?, sellerId: String?, status: ProductStatus?, restrictToActive: Boolean): Pair<List<Product>, String?> = withConnection { connection ->
        val values = mutableListOf<Any>(); val clauses = mutableListOf("1=1")
        if (status != null) { clauses += "p.status = ?"; values += status.name } else if (restrictToActive) clauses += "p.status = 'ACTIVE'"
        categoryId?.let { clauses += "p.category_id = ?"; values += it }
        sellerId?.let { clauses += "p.seller_id = ?"; values += it }
        cursor?.let { decodeCursor(it)?.let { (created, id) -> clauses += "(p.created_at, p.id) < (?, ?)"; values += Timestamp.from(created); values += id } }
        val sql = "SELECT p.* FROM products p WHERE ${clauses.joinToString(" AND ")} ORDER BY p.created_at DESC, p.id DESC LIMIT ?"
        connection.prepareStatement(sql).use { statement -> values.forEachIndexed { index, value -> when (value) { is String -> statement.setString(index + 1, value); is Timestamp -> statement.setTimestamp(index + 1, value) } }; statement.setInt(values.size + 1, limit + 1); statement.executeQuery().use { result -> val rows = buildList { while (result.next()) add(result.product(connection, json)) }; val page = rows.take(limit); Pair(page, if (rows.size > limit) encodeCursor(page.last()) else null) } }
    }

    override fun find(id: String, publicOnly: Boolean): Product? = withConnection { connection -> get(connection, id, publicOnly) }
    override fun findBySlug(slug: String): Product? = withConnection { connection -> connection.prepareStatement("SELECT * FROM products WHERE slug=? AND status='ACTIVE'").use { statement -> statement.setString(1, slug); statement.executeQuery().use { result -> if (result.next()) result.product(connection, json) else null } } }

    override fun create(input: ProductInput, actorId: String, correlationId: String): Product = transaction { connection ->
        validate(input)
        val id = CommerceId.new("prd").value; val now = Instant.now()
        try {
            insertProduct(connection, id, input, now)
            input.variants.forEach { insertVariant(connection, id, it, now) }
            input.media.forEach { insertMedia(connection, id, it) }
            val product = get(connection, id, false)!!
            history(connection, id, null, input.status, actorId, now); outbox(connection, product, "ProductCreated", correlationId, now); input.variants.forEach { outbox(connection, product, "ProductVariantCreated", correlationId, now) }; product
        } catch (error: Exception) { if (error is SQLException && error.sqlState == "23505") throw ApiException(ErrorCode.CONFLICT, "Product slug or SKU already exists.", 409); throw error }
    }

    override fun update(id: String, input: ProductInput, actorId: String, correlationId: String): Product = transaction { connection ->
        validate(input); val existing = get(connection, id, false) ?: throw ApiException(ErrorCode.NOT_FOUND, "Product not found.", 404); checkOwnership(existing, actorId, input.ownerType, input.sellerId)
        val now = Instant.now()
        try {
            connection.prepareStatement("UPDATE products SET seller_id=?,owner_type=?,brand_id=?,category_id=?,name=?,slug=?,description=?,short_description=?,sku_reference=?,status=?,tax_category=?,attributes=?::jsonb,seo_title=?,seo_description=?,canonical_url=?,version=version+1,updated_at=? WHERE id=?").use { statement -> statement.setString(1, input.sellerId); statement.setString(2, input.ownerType.name); statement.setString(3, input.brandId); statement.setString(4, input.categoryId); statement.setString(5, input.name.trim()); statement.setString(6, input.slug); statement.setString(7, input.description.trim()); statement.setString(8, input.shortDescription); statement.setString(9, input.skuReference); statement.setString(10, input.status.name); statement.setString(11, input.taxCategory); statement.setString(12, json.encodeToString(input.attributes)); statement.setString(13, input.seoTitle); statement.setString(14, input.seoDescription); statement.setString(15, input.canonicalUrl); statement.setTimestamp(16, now.timestamp()); statement.setString(17, id); statement.executeUpdate() }
            connection.prepareStatement("DELETE FROM product_variants WHERE product_id=?").use { statement -> statement.setString(1, id); statement.executeUpdate() }; input.variants.forEach { insertVariant(connection, id, it, now) }; connection.prepareStatement("DELETE FROM product_media WHERE product_id=?").use { statement -> statement.setString(1, id); statement.executeUpdate() }; input.media.forEach { insertMedia(connection, id, it) }
            val product = get(connection, id, false)!!; history(connection, id, existing.status, input.status, actorId, now); outbox(connection, product, "ProductUpdated", correlationId, now); product
        } catch (error: Exception) { if (error is SQLException && error.sqlState == "23505") throw ApiException(ErrorCode.CONFLICT, "Product slug or SKU already exists.", 409); throw error }
    }

    override fun changeStatus(id: String, status: ProductStatus, actorId: String, correlationId: String): Product = transaction { connection ->
        val existing = get(connection, id, false) ?: throw ApiException(ErrorCode.NOT_FOUND, "Product not found.", 404); checkOwnership(existing, actorId, existing.ownerType, existing.sellerId); val now = Instant.now(); connection.prepareStatement("UPDATE products SET status=?,version=version+1,updated_at=? WHERE id=?").use { statement -> statement.setString(1, status.name); statement.setTimestamp(2, now.timestamp()); statement.setString(3, id); statement.executeUpdate() }; val product = get(connection, id, false)!!; history(connection, id, existing.status, status, actorId, now); outbox(connection, product, "Product${status.name.replaceFirstChar { it.titlecase() }}", correlationId, now); product
    }

    override fun delete(id: String, actorId: String, correlationId: String) = transaction { connection -> val existing = get(connection, id, false) ?: throw ApiException(ErrorCode.NOT_FOUND, "Product not found.", 404); checkOwnership(existing, actorId, existing.ownerType, existing.sellerId); val now = Instant.now(); connection.prepareStatement("UPDATE products SET status='ARCHIVED',version=version+1,updated_at=? WHERE id=?").use { statement -> statement.setTimestamp(1, now.timestamp()); statement.setString(2, id); statement.executeUpdate() }; val product = get(connection, id, false)!!; history(connection, id, existing.status, ProductStatus.ARCHIVED, actorId, now); outbox(connection, product, "ProductDeleted", correlationId, now) }

    private fun checkOwnership(product: Product, actorId: String, ownerType: OwnerType, requestedSellerId: String) { if (product.ownerType == OwnerType.SELLER && product.sellerId != actorId) throw ApiException(ErrorCode.FORBIDDEN, "You do not own this product.", 403); if (ownerType == OwnerType.SELLER && requestedSellerId != actorId) throw ApiException(ErrorCode.FORBIDDEN, "Seller ownership must come from the access token.", 403) }
    private fun validate(input: ProductInput) { validateProductName(input.name); validateProductSlug(input.slug); if (input.description.isBlank()) throw ApiException(ErrorCode.VALIDATION_ERROR, "Description is required.", 400); if (input.categoryId.isBlank()) throw ApiException(ErrorCode.VALIDATION_ERROR, "Category is required.", 400); input.variants.forEach { if (it.sku.isBlank() || it.weightGrams != null && it.weightGrams <= 0) throw ApiException(ErrorCode.VALIDATION_ERROR, "Variant is invalid.", 400) } }
    private fun insertProduct(connection: Connection, id: String, input: ProductInput, now: Instant) = connection.prepareStatement("INSERT INTO products (id,seller_id,owner_type,brand_id,category_id,name,slug,description,short_description,sku_reference,status,tax_category,attributes,seo_title,seo_description,canonical_url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?::jsonb,?,?,?,?,?)").use { statement -> statement.setString(1, id); statement.setString(2, input.sellerId); statement.setString(3, input.ownerType.name); statement.setString(4, input.brandId); statement.setString(5, input.categoryId); statement.setString(6, input.name.trim()); statement.setString(7, input.slug); statement.setString(8, input.description.trim()); statement.setString(9, input.shortDescription); statement.setString(10, input.skuReference); statement.setString(11, input.status.name); statement.setString(12, input.taxCategory); statement.setString(13, json.encodeToString(input.attributes)); statement.setString(14, input.seoTitle); statement.setString(15, input.seoDescription); statement.setString(16, input.canonicalUrl); statement.setTimestamp(17, now.timestamp()); statement.setTimestamp(18, now.timestamp()); statement.executeUpdate() }
    private fun insertVariant(connection: Connection, productId: String, input: VariantInput, now: Instant) { val id = CommerceId.new("var").value; connection.prepareStatement("INSERT INTO product_variants (id,product_id,sku,barcode,attributes,price_reference,weight_grams,dimensions,status,created_at,updated_at) VALUES (?,?,?,?,?::jsonb,?,?,?::jsonb,?,?,?)").use { statement -> statement.setString(1, id); statement.setString(2, productId); statement.setString(3, input.sku); statement.setString(4, input.barcode); statement.setString(5, json.encodeToString(input.attributes)); statement.setString(6, input.priceReference); if (input.weightGrams == null) statement.setNull(7, java.sql.Types.INTEGER) else statement.setInt(7, input.weightGrams); statement.setString(8, json.encodeToString(input.dimensions)); statement.setString(9, input.status.name); statement.setTimestamp(10, now.timestamp()); statement.setTimestamp(11, now.timestamp()); statement.executeUpdate() } }
    private fun insertMedia(connection: Connection, productId: String, input: MediaInput) = connection.prepareStatement("INSERT INTO product_media (product_id,media_id,media_type,url,sort_order,alt_text) VALUES (?,?,?,?,?,?)").use { statement -> statement.setString(1, productId); statement.setString(2, input.mediaId); statement.setString(3, input.mediaType); statement.setString(4, input.url); statement.setInt(5, input.sortOrder); statement.setString(6, input.altText); statement.executeUpdate() }
    private fun history(connection: Connection, productId: String, from: ProductStatus?, to: ProductStatus, actorId: String, now: Instant) = connection.prepareStatement("INSERT INTO product_status_history (id,product_id,from_status,to_status,changed_by,changed_at) VALUES (?,?,?,?,?,?)").use { statement -> statement.setString(1, CommerceId.new("pst").value); statement.setString(2, productId); statement.setString(3, from?.name); statement.setString(4, to.name); statement.setString(5, actorId); statement.setTimestamp(6, now.timestamp()); statement.executeUpdate() }
    private fun outbox(connection: Connection, product: Product, type: String, correlationId: String, now: Instant) = connection.prepareStatement("INSERT INTO catalog_outbox_events (id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json) VALUES (?,?,?,?,1,?,?,?::jsonb)").use { statement -> statement.setString(1, newOutboxId()); statement.setString(2, "Product"); statement.setString(3, product.id); statement.setString(4, type); statement.setTimestamp(5, now.timestamp()); statement.setString(6, correlationId); statement.setString(7, json.encodeToString(ProductEventPayload(product.id, product.slug, product.categoryId, product.status.name, product.version, product.name, product.description, product.shortDescription, product.brandId, product.attributes, product.media))); statement.executeUpdate() }
    private fun get(connection: Connection, id: String, publicOnly: Boolean): Product? = connection.prepareStatement("SELECT * FROM products WHERE id=?${if (publicOnly) " AND status='ACTIVE'" else ""}").use { statement -> statement.setString(1, id); statement.executeQuery().use { result -> if (result.next()) result.product(connection, json) else null } }
    override fun unpublished(limit: Int): List<ServiceOutboxRecord> = withConnection { connection -> connection.prepareStatement("SELECT id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json::text FROM catalog_outbox_events WHERE published_at IS NULL ORDER BY occurred_at LIMIT ?").use { statement -> statement.setInt(1, limit); statement.executeQuery().use { result -> buildList { while (result.next()) add(ServiceOutboxRecord(result.getString(1), result.getString(2), result.getString(3), result.getString(4), result.getInt(5), result.getTimestamp(6).toInstant(), result.getString(7), result.getString(8))) } } } }
    override fun markPublished(ids: List<String>, publishedAt: Instant) { transaction { connection -> connection.prepareStatement("UPDATE catalog_outbox_events SET published_at=? WHERE id=ANY(?)").use { statement -> statement.setTimestamp(1, publishedAt.timestamp()); statement.setArray(2, connection.createArrayOf("varchar", ids.toTypedArray())); statement.executeUpdate() } } }
    private fun <T> withConnection(block: (Connection) -> T): T = dataSource.connection.use(block)
    private fun <T> transaction(block: (Connection) -> T): T = dataSource.connection.use { connection -> connection.autoCommit = false; try { block(connection).also { connection.commit() } } catch (error: Throwable) { connection.rollback(); throw error } }
}

private fun ResultSet.product(connection: Connection, json: Json): Product { val id = getString("id"); val variants = connection.prepareStatement("SELECT * FROM product_variants WHERE product_id=? ORDER BY id").use { statement -> statement.setString(1, id); statement.executeQuery().use { result -> buildList { while (result.next()) add(result.variant(json)) } } }; val media = connection.prepareStatement("SELECT * FROM product_media WHERE product_id=? ORDER BY sort_order,media_id").use { statement -> statement.setString(1, id); statement.executeQuery().use { result -> buildList { while (result.next()) add(ProductMedia(result.getString("media_id"), result.getString("media_type"), result.getString("url"), result.getInt("sort_order"), result.getString("alt_text"))) } } }; return Product(id, getString("seller_id"), OwnerType.valueOf(getString("owner_type")), getString("brand_id"), getString("category_id"), getString("name"), getString("slug"), getString("description"), getString("short_description"), getString("sku_reference"), ProductStatus.valueOf(getString("status")), getString("tax_category"), json.decodeFromString(getString("attributes")), getString("seo_title"), getString("seo_description"), getString("canonical_url"), getLong("version"), getTimestamp("created_at").toInstant().toString(), getTimestamp("updated_at").toInstant().toString(), variants, media) }
private fun ResultSet.variant(json: Json): ProductVariant = ProductVariant(getString("id"), getString("product_id"), getString("sku"), getString("barcode"), json.decodeFromString(getString("attributes")), getString("price_reference"), getInt("weight_grams").takeUnless { wasNull() }, json.decodeFromString(getString("dimensions")), VariantStatus.valueOf(getString("status")))
private fun encodeCursor(product: Product): String = java.util.Base64.getUrlEncoder().withoutPadding().encodeToString("${product.createdAt}|${product.id}".toByteArray())
private fun decodeCursor(cursor: String): Pair<Instant, String>? = runCatching { String(java.util.Base64.getUrlDecoder().decode(cursor)).split('|').let { Instant.parse(it[0]) to it[1] } }.getOrNull()
private fun Instant.timestamp(): Timestamp = Timestamp.from(this)
