package com.ecommerce.refund

import com.ecommerce.platform.common.CommerceId
import com.ecommerce.platform.error.ApiException
import com.ecommerce.platform.error.ErrorCode
import com.ecommerce.platform.service.InternalHttpClient
import com.ecommerce.platform.service.ServiceOutboxRecord
import com.ecommerce.platform.service.ServiceOutboxStore
import com.ecommerce.platform.service.newOutboxId
import kotlinx.serialization.json.Json
import java.security.MessageDigest
import java.sql.Connection
import java.sql.ResultSet
import java.sql.Timestamp
import java.time.Instant
import javax.sql.DataSource

class RefundRepository(private val dataSource:DataSource,private val paymentClient:InternalHttpClient,private val internalHeaders:Map<String,String>):ServiceOutboxStore{
    private val json=Json{encodeDefaults=true;explicitNulls=false;ignoreUnknownKeys=true}
    fun create(userId:String,request:RefundRequest,key:String,correlation:String):RefundResponse{if(request.orderId.isBlank()||request.paymentId.isBlank()||request.amountMinor<=0||request.reason.isBlank()||!request.currency.matches(Regex("[A-Z]{3}")))throw ApiException(ErrorCode.VALIDATION_ERROR,"Refund request is invalid.",400);val hash=sha(json.encodeToString(request));return transaction{c->val prior=c.prepareStatement("SELECT request_hash,id FROM refunds WHERE user_id=? AND idempotency_key=?").use{s->s.setString(1,userId);s.setString(2,key);s.executeQuery().use{r->if(r.next()){if(r.getString(1)!=hash)throw ApiException(ErrorCode.CONFLICT,"Refund idempotency key was reused.",409);return@transaction get(c,r.getString(2))!!}else null}};val now=Instant.now();val id=CommerceId.new("rfd").value;c.prepareStatement("INSERT INTO refunds(id,user_id,order_id,payment_id,amount_minor,currency,type,status,reason,idempotency_key,request_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,userId);s.setString(3,request.orderId);s.setString(4,request.paymentId);s.setLong(5,request.amountMinor);s.setString(6,request.currency);s.setString(7,request.type.name);s.setString(8,RefundStatus.REQUESTED.name);s.setString(9,request.reason);s.setString(10,key);s.setString(11,hash);s.setTimestamp(12,now.ts());s.setTimestamp(13,now.ts());s.executeUpdate()};request.items.forEach{item->c.prepareStatement("INSERT INTO refund_items(refund_id,variant_id,quantity,amount_minor) VALUES(?,?,?,?)").use{s->s.setString(1,id);s.setString(2,item.variantId);s.setInt(3,item.quantity);s.setLong(4,item.amountMinor);s.executeUpdate()}};history(c,id,null,RefundStatus.REQUESTED,userId,request.reason,now);val response=get(c,id)!!;outbox(c,response,"RefundRequested",correlation,now);response}}
    fun getOwned(userId:String,id:String)=withConnection{get(it,id,userId)}
    fun listOwned(userId:String): List<RefundResponse> = withConnection{c->c.prepareStatement("SELECT id FROM refunds WHERE user_id=? ORDER BY created_at DESC LIMIT 100").use{s->s.setString(1,userId);s.executeQuery().use{r->buildList{while(r.next())get(c,r.getString(1))?.let(::add)}}}}
    fun approve(id:String,decision:RefundDecision,actor:String,correlation:String):RefundResponse{val current=transaction{c->val value=get(c,id,null,true)?:throw ApiException(ErrorCode.NOT_FOUND,"Refund not found.",404);if(value.status!=RefundStatus.REQUESTED&&value.status!=RefundStatus.PROCESSING)throw ApiException(ErrorCode.CONFLICT,"Refund is not awaiting approval or recovery.",409);if(!decision.approve){if(value.status!=RefundStatus.REQUESTED)throw ApiException(ErrorCode.CONFLICT,"A processing refund cannot be rejected.",409);val now=Instant.now();c.prepareStatement("UPDATE refunds SET status='REJECTED',updated_at=? WHERE id=?").use{s->s.setTimestamp(1,now.ts());s.setString(2,id);s.executeUpdate()};history(c,id,value.status,RefundStatus.REJECTED,actor,decision.reason,now);return@transaction get(c,id)!!};if(value.status==RefundStatus.REQUESTED){val now=Instant.now();c.prepareStatement("UPDATE refunds SET status='PROCESSING',updated_at=? WHERE id=?").use{s->s.setTimestamp(1,now.ts());s.setString(2,id);s.executeUpdate()};history(c,id,value.status,RefundStatus.PROCESSING,actor,decision.reason,now)};get(c,id)!!};if(!decision.approve)return current;val body="""{"amountMinor":${current.amountMinor},"currency":"${current.currency}","idempotencyKey":"refund-${current.id}"}""";val response=paymentClient.post("/api/v1/internal/payments/${current.paymentId}/refund",body,internalHeaders);if(response.statusCode !in 200..299)throw ApiException(ErrorCode.DEPENDENCY_UNAVAILABLE,"Payment refund is unavailable.",503,true);val paymentRefund=json.decodeFromString<PaymentRefundResult>(response.body);return transaction{c->val now=Instant.now();c.prepareStatement("UPDATE refunds SET status='COMPLETED',provider_refund_id=?,updated_at=? WHERE id=?").use{s->s.setString(1,paymentRefund.providerRefundId);s.setTimestamp(2,now.ts());s.setString(3,id);s.executeUpdate()};history(c,id,RefundStatus.PROCESSING,RefundStatus.COMPLETED,actor,"payment-refund-completed",now);val result=get(c,id)!!;outbox(c,result,"RefundCompleted",correlation,now);result}}
    private fun get(c:Connection,id:String,userId:String?=null,lock:Boolean=false):RefundResponse?{val sql=if(userId==null)"SELECT * FROM refunds WHERE id${if(lock)" FOR UPDATE" else ""}" else "SELECT * FROM refunds WHERE id=? AND user_id=?${if(lock)" FOR UPDATE" else ""}";val fixed=if(userId==null)"SELECT * FROM refunds WHERE id=?${if(lock)" FOR UPDATE" else ""}" else sql;return c.prepareStatement(fixed).use{s->s.setString(1,id);if(userId!=null)s.setString(2,userId);s.executeQuery().use{r->if(r.next())response(c,r)else null}}}
    private fun response(c:Connection,r:ResultSet):RefundResponse{val id=r.getString("id");val items=c.prepareStatement("SELECT variant_id,quantity,amount_minor FROM refund_items WHERE refund_id=?").use{s->s.setString(1,id);s.executeQuery().use{x->buildList{while(x.next())add(RefundItem(x.getString(1),x.getInt(2),x.getLong(3)))}}};return RefundResponse(id,r.getString("user_id"),r.getString("order_id"),r.getString("payment_id"),r.getLong("amount_minor"),r.getString("currency"),RefundType.valueOf(r.getString("type")),RefundStatus.valueOf(r.getString("status")),r.getString("reason"),items,r.getString("provider_refund_id"),r.getTimestamp("created_at").toInstant().toString(),r.getTimestamp("updated_at").toInstant().toString())}
    private fun history(c:Connection,id:String,from:RefundStatus?,to:RefundStatus,actor:String,reason:String?,now:Instant)=c.prepareStatement("INSERT INTO refund_status_history(id,refund_id,from_status,to_status,actor_id,reason,created_at) VALUES(?,?,?,?,?,?,?)").use{s->s.setString(1,CommerceId.new("rfh").value);s.setString(2,id);s.setString(3,from?.name);s.setString(4,to.name);s.setString(5,actor);s.setString(6,reason);s.setTimestamp(7,now.ts());s.executeUpdate()}
    private fun outbox(c:Connection,value:RefundResponse,type:String,correlation:String,now:Instant)=c.prepareStatement("INSERT INTO refund_outbox_events(id,aggregate_id,event_type,occurred_at,correlation_id,payload_json) VALUES(?,?,?,?,?,?::jsonb)").use{s->s.setString(1,newOutboxId());s.setString(2,value.id);s.setString(3,type);s.setTimestamp(4,now.ts());s.setString(5,correlation);s.setString(6,json.encodeToString(value));s.executeUpdate()}
    override fun unpublished(limit:Int):List<ServiceOutboxRecord> = withConnection{c->c.prepareStatement("SELECT id,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json::text FROM refund_outbox_events WHERE published_at IS NULL ORDER BY occurred_at LIMIT ?").use{s->s.setInt(1,limit);s.executeQuery().use{r->buildList{while(r.next())add(ServiceOutboxRecord(r.getString(1),"Refund",r.getString(2),r.getString(3),r.getInt(4),r.getTimestamp(5).toInstant(),r.getString(6),r.getString(7)))}}}}
    override fun markPublished(ids:List<String>,publishedAt:Instant){if(ids.isEmpty())return;transaction{c->c.prepareStatement("UPDATE refund_outbox_events SET published_at=? WHERE id=ANY(?)").use{s->s.setTimestamp(1,publishedAt.ts());s.setArray(2,c.createArrayOf("varchar",ids.toTypedArray()));s.executeUpdate()}}}
    private fun sha(v:String)=MessageDigest.getInstance("SHA-256").digest(v.toByteArray()).joinToString(""){ "%02x".format(it) }
    private fun <T>withConnection(block:(Connection)->T):T=dataSource.connection.use(block)
    private fun <T>transaction(block:(Connection)->T):T=dataSource.connection.use{c->c.autoCommit=false;try{block(c).also{c.commit()}}catch(e:Throwable){c.rollback();throw e}}
}
private fun Instant.ts()=Timestamp.from(this)
