CREATE TABLE analytics_inbox_events (event_id VARCHAR(120) PRIMARY KEY, event_type VARCHAR(120) NOT NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE analytics_applied_events (event_id VARCHAR(120) NOT NULL, projection VARCHAR(60) NOT NULL, applied_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(event_id,projection));
CREATE TABLE analytics_events (event_id VARCHAR(120) PRIMARY KEY, event_type VARCHAR(120) NOT NULL, occurred_at TIMESTAMPTZ NOT NULL, producer VARCHAR(120) NOT NULL, aggregate_id VARCHAR(120) NOT NULL, user_hash VARCHAR(128), metric_json JSONB NOT NULL);
CREATE TABLE analytics_hourly (bucket TIMESTAMPTZ PRIMARY KEY, events BIGINT NOT NULL DEFAULT 0, views BIGINT NOT NULL DEFAULT 0, searches BIGINT NOT NULL DEFAULT 0, carts BIGINT NOT NULL DEFAULT 0, orders BIGINT NOT NULL DEFAULT 0, paid_orders BIGINT NOT NULL DEFAULT 0, checkouts BIGINT NOT NULL DEFAULT 0, revenue_minor BIGINT NOT NULL DEFAULT 0);
CREATE TABLE analytics_daily (bucket DATE PRIMARY KEY, events BIGINT NOT NULL DEFAULT 0, views BIGINT NOT NULL DEFAULT 0, searches BIGINT NOT NULL DEFAULT 0, carts BIGINT NOT NULL DEFAULT 0, orders BIGINT NOT NULL DEFAULT 0, paid_orders BIGINT NOT NULL DEFAULT 0, checkouts BIGINT NOT NULL DEFAULT 0, revenue_minor BIGINT NOT NULL DEFAULT 0);
CREATE TABLE analytics_product_metrics (bucket DATE NOT NULL, product_id VARCHAR(120) NOT NULL, views BIGINT NOT NULL DEFAULT 0, orders BIGINT NOT NULL DEFAULT 0, revenue_minor BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(bucket,product_id));
CREATE TABLE analytics_seller_metrics (bucket DATE NOT NULL, seller_id VARCHAR(120) NOT NULL, orders BIGINT NOT NULL DEFAULT 0, revenue_minor BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(bucket,seller_id));
CREATE TABLE analytics_replay_audit (run_id VARCHAR(120) NOT NULL, event_id VARCHAR(120) NOT NULL, replayed_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(run_id,event_id));
CREATE TABLE analytics_dlq (id BIGSERIAL PRIMARY KEY, event_id VARCHAR(120), error_text TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
