package com.ecommerce.order

import com.ecommerce.platform.common.CommerceId
import com.ecommerce.platform.error.ApiException
import com.ecommerce.platform.error.ErrorCode
import com.ecommerce.platform.service.ServiceOutboxRecord
import com.ecommerce.platform.service.ServiceOutboxStore
import com.ecommerce.platform.service.newOutboxId
import kotlinx.serialization.json.Json
import java.security.MessageDigest
import java.sql.Connection
import java.sql.ResultSet
import java.sql.SQLException
import java.sql.Timestamp
import java.time.Instant
import java.util.Base64
import javax.sql.DataSource

class OrderRepository(private val dataSource: DataSource) : ServiceOutboxStore, OrderStore {
    private val json = Json { encodeDefaults = true; explicitNulls = false; ignoreUnknownKeys = true }

    override fun create(userId: String, request: OrderCreateRequest, idempotencyKey: String, actorId: String, correlationId: String): OrderResponse = transaction { connection ->
        validate(request)
        val hash = sha256(json.encodeToString(request))
        val prior = connection.prepareStatement("SELECT request_hash,id FROM orders WHERE user_id=? AND idempotency_key=?").use { statement -> statement.setString(1, userId); statement.setString(2, idempotencyKey); statement.executeQuery().use { if (it.next()) it.getString(1) to it.getString(2) else null } }
        if (prior != null) { if (prior.first != hash) throw ApiException(ErrorCode.CONFLICT, "Idempotency key was reused with a different order request.", 409); return@transaction get(connection, prior.second)!! }
        val now = Instant.now(); val id = CommerceId.new("ord").value
        try {
            connection.prepareStatement("INSERT INTO orders(id,user_id,checkout_id,reservation_id,status,subtotal_minor,item_discount_minor,promotion_discount_minor,shipping_minor,tax_minor,total_minor,currency,idempotency_key,request_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").use { statement ->
                statement.setString(1, id); statement.setString(2, userId); statement.setString(3, request.checkoutId); statement.setString(4, request.reservationId); statement.setString(5, request.initialStatus.name); statement.setLong(6, request.subtotalMinor); statement.setLong(7, request.itemDiscountMinor); statement.setLong(8, request.promotionDiscountMinor); statement.setLong(9, request.shippingMinor); statement.setLong(10, request.taxMinor); statement.setLong(11, request.totalMinor); statement.setString(12, request.currency); statement.setString(13, idempotencyKey); statement.setString(14, hash); statement.setTimestamp(15, now.timestamp()); statement.setTimestamp(16, now.timestamp()); statement.executeUpdate()
            }
        } catch (error: SQLException) { if (error.sqlState == "23505") throw ApiException(ErrorCode.CONFLICT, "Order or checkout already exists.", 409); throw error }
        request.items.forEach { item -> connection.prepareStatement("INSERT INTO order_items(id,order_id,product_id,variant_id,product_name,sku,seller_id,quantity,unit_price_minor,tax_minor,discount_minor,line_total_minor,currency,price_version,attributes_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?::jsonb)").use { statement -> statement.setString(1, CommerceId.new("oi").value); statement.setString(2, id); statement.setString(3, item.productId); statement.setString(4, item.variantId); statement.setString(5, item.productName); statement.setString(6, item.sku); statement.setString(7, item.sellerId); statement.setInt(8, item.quantity); statement.setLong(9, item.unitPriceMinor); statement.setLong(10, item.taxMinor); statement.setLong(11, item.discountMinor); statement.setLong(12, item.lineTotalMinor); statement.setString(13, item.currency); statement.setString(14, item.priceVersion); statement.setString(15, json.encodeToString(item.attributes)); statement.executeUpdate() } }
        address(connection, id, "SHIPPING", request.shippingAddress); address(connection, id, "BILLING", request.billingAddress)
        request.items.forEach { item -> connection.prepareStatement("INSERT INTO order_price_snapshots(id,order_id,variant_id,unit_price_minor,tax_minor,discount_minor,price_version,currency) VALUES (?,?,?,?,?,?,?,?)").use { statement -> statement.setString(1, CommerceId.new("price").value); statement.setString(2, id); statement.setString(3, item.variantId); statement.setLong(4, item.unitPriceMinor); statement.setLong(5, item.taxMinor); statement.setLong(6, item.discountMinor); statement.setString(7, item.priceVersion.ifBlank { "checkout-${request.checkoutId}" }); statement.setString(8, item.currency); statement.executeUpdate() } }
        request.promotion?.let { promotion -> connection.prepareStatement("INSERT INTO order_promotion_snapshots(order_id,promotion_id,coupon_code,discount_minor,allocation_json) VALUES (?,?,?,?,?::jsonb)").use { statement -> statement.setString(1, id); statement.setString(2, promotion.promotionId); statement.setString(3, promotion.couponCode); statement.setLong(4, promotion.discountMinor); statement.setString(5, json.encodeToString(promotion.allocation)); statement.executeUpdate() } }
        history(connection, id, null, request.initialStatus, actorId, "order-created", now)
        val response = get(connection, id)!!; outbox(connection, response, "OrderCreated", correlationId, now); if (request.initialStatus == OrderStatus.INVENTORY_RESERVED) outbox(connection, response, "OrderInventoryReserved", correlationId, now); response
    }

    override fun getOwned(userId: String, id: String): OrderResponse? = withConnection { connection -> get(connection, id, userId) }
    override fun listOwned(userId: String, cursor: String?, limit: Int): Pair<List<OrderResponse>, String?> = withConnection { connection -> page(connection, "WHERE user_id=?", listOf(userId), cursor, limit) }
    override fun listAll(cursor: String?, limit: Int): Pair<List<OrderResponse>, String?> = withConnection { connection -> page(connection, "", emptyList(), cursor, limit) }

    override fun transition(id: String, userId: String?, target: OrderStatus, actorId: String, reason: String?, correlationId: String): OrderResponse = transaction { connection ->
        val current = get(connection, id, userId, true) ?: throw ApiException(ErrorCode.NOT_FOUND, "Order not found.", 404)
        if (current.status == target) return@transaction current
        try { assertOrderTransition(current.status, target) } catch (_: IllegalStateException) { throw ApiException(ErrorCode.CONFLICT, "Order cannot transition from ${current.status} to $target.", 409) }
        val now = Instant.now(); connection.prepareStatement("UPDATE orders SET status=?,version=version+1,updated_at=? WHERE id=?").use { statement -> statement.setString(1, target.name); statement.setTimestamp(2, now.timestamp()); statement.setString(3, id); statement.executeUpdate() }; history(connection, id, current.status, target, actorId, reason, now); val response = get(connection, id)!!; outbox(connection, response, eventType(target), correlationId, now); response
    }

    override fun cancel(id: String, userId: String, reason: String, actorId: String, correlationId: String): OrderResponse = transaction { connection ->
        val current = get(connection, id, userId, true) ?: throw ApiException(ErrorCode.NOT_FOUND, "Order not found.", 404)
        if (current.status == OrderStatus.CANCELLED) return@transaction current
        val target = when (current.status) { OrderStatus.CREATED, OrderStatus.VALIDATING, OrderStatus.INVENTORY_RESERVED, OrderStatus.PAYMENT_PENDING -> OrderStatus.CANCELLED; OrderStatus.PAID, OrderStatus.CONFIRMED, OrderStatus.PROCESSING -> OrderStatus.CANCEL_REQUESTED; else -> throw ApiException(ErrorCode.CONFLICT, "Order cannot be cancelled from ${current.status}.", 409) }
        val now = Instant.now(); connection.prepareStatement("UPDATE orders SET status=?,version=version+1,updated_at=? WHERE id=?").use { statement -> statement.setString(1, target.name); statement.setTimestamp(2, now.timestamp()); statement.setString(3, id); statement.executeUpdate() }; history(connection, id, current.status, target, actorId, reason, now); connection.prepareStatement("INSERT INTO order_cancellations(id,order_id,reason,requested_by,created_at) VALUES (?,?,?,?,?) ON CONFLICT(order_id) DO NOTHING").use { statement -> statement.setString(1, CommerceId.new("cancel").value); statement.setString(2, id); statement.setString(3, reason); statement.setString(4, actorId); statement.setTimestamp(5, now.timestamp()); statement.executeUpdate() }; val response = get(connection, id)!!; outbox(connection, response, if (target == OrderStatus.CANCELLED) "OrderCancelled" else "OrderCancellationRequested", correlationId, now); response
    }

    override fun requestReturn(id: String, userId: String, request: ReturnRequest, actorId: String, correlationId: String): ReturnResponse = transaction { connection ->
        if (request.reason.isBlank() || request.items.isEmpty() || request.items.any { it.quantity <= 0 }) throw ApiException(ErrorCode.VALIDATION_ERROR, "Return request is invalid.", 400)
        val order = get(connection, id, userId, true) ?: throw ApiException(ErrorCode.NOT_FOUND, "Order not found.", 404)
        val existing = latestReturn(connection, id)
        if (existing != null && order.status == OrderStatus.RETURN_REQUESTED) return@transaction existing
        if (order.status != OrderStatus.DELIVERED) throw ApiException(ErrorCode.CONFLICT, "Only delivered orders can be returned.", 409)
        request.items.forEach { requested -> val item = order.items.find { it.variantId == requested.variantId } ?: throw ApiException(ErrorCode.VALIDATION_ERROR, "Return item is not part of the order.", 400); if (requested.quantity > item.quantity) throw ApiException(ErrorCode.VALIDATION_ERROR, "Return quantity exceeds the ordered quantity.", 400) }
        val now = Instant.now(); val returnId = CommerceId.new("ret").value; connection.prepareStatement("INSERT INTO order_returns(id,order_id,status,reason,requested_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").use { statement -> statement.setString(1, returnId); statement.setString(2, id); statement.setString(3, "REQUESTED"); statement.setString(4, request.reason); statement.setString(5, actorId); statement.setTimestamp(6, now.timestamp()); statement.setTimestamp(7, now.timestamp()); statement.executeUpdate() }; request.items.forEach { item -> connection.prepareStatement("INSERT INTO order_return_items(return_id,variant_id,quantity) VALUES (?,?,?)").use { statement -> statement.setString(1, returnId); statement.setString(2, item.variantId); statement.setInt(3, item.quantity); statement.executeUpdate() } }
        connection.prepareStatement("UPDATE orders SET status='RETURN_REQUESTED',version=version+1,updated_at=? WHERE id=?").use { statement -> statement.setTimestamp(1, now.timestamp()); statement.setString(2, id); statement.executeUpdate() }; history(connection, id, OrderStatus.DELIVERED, OrderStatus.RETURN_REQUESTED, actorId, request.reason, now); val response = ReturnResponse(returnId, id, "REQUESTED", request.reason, request.items, now.toString()); outbox(connection, get(connection, id)!!, "OrderReturnRequested", correlationId, now); response
    }

    fun returnById(userId: String, returnId: String): ReturnResponse? = withConnection { connection -> val sql = "SELECT r.*, i.variant_id, i.quantity FROM order_returns r LEFT JOIN order_return_items i ON i.return_id=r.id JOIN orders o ON o.id=r.order_id WHERE r.id=? AND o.user_id=? ORDER BY i.variant_id"; connection.prepareStatement(sql).use { statement -> statement.setString(1, returnId); statement.setString(2, userId); statement.executeQuery().use { result -> if (!result.next()) null else { val items = buildList { do { add(ReturnItemRequest(result.getString("variant_id"), result.getInt("quantity"))) } while (result.next()) }; ReturnResponse(result.getString("id"), result.getString("order_id"), result.getString("status"), result.getString("reason"), items, result.getTimestamp("created_at").toInstant().toString()) } } } }

    private fun validate(request: OrderCreateRequest) { if (request.checkoutId.isBlank() || request.items.isEmpty() || !request.currency.matches(Regex("[A-Z]{3}")) || request.items.any { it.quantity <= 0 || it.unitPriceMinor < 0 || it.taxMinor < 0 || it.discountMinor < 0 || it.lineTotalMinor < 0 }) throw ApiException(ErrorCode.VALIDATION_ERROR, "Order snapshot is invalid.", 400); val subtotal = request.items.sumOf { it.unitPriceMinor * it.quantity }; if (subtotal != request.subtotalMinor || request.totalMinor != request.subtotalMinor - request.itemDiscountMinor - request.promotionDiscountMinor + request.shippingMinor + request.taxMinor || request.totalMinor < 0) throw ApiException(ErrorCode.CONFLICT, "Order totals do not reconcile.", 409) }
    private fun page(connection: Connection, where: String, args: List<String>, cursor: String?, limit: Int): Pair<List<OrderResponse>, String?> { val size = limit.coerceIn(1, 50); val decoded = cursor?.let(::decodeCursor); val clause = when { where.isBlank() && decoded == null -> ""; where.isBlank() -> "WHERE (created_at,id) < (?,?)"; decoded == null -> where; else -> "$where AND (created_at,id) < (?,?)" }; val sql = "SELECT id FROM orders $clause ORDER BY created_at DESC,id DESC LIMIT ?"; val ids = connection.prepareStatement(sql).use { statement -> var index=1; args.forEach { statement.setString(index++, it) }; if (decoded != null) { statement.setTimestamp(index++, Timestamp.from(decoded.first)); statement.setString(index++, decoded.second) }; statement.setInt(index, size+1); statement.executeQuery().use { result -> buildList { while (result.next()) add(result.getString(1)) } } }; val more=ids.size>size; val selected=ids.take(size).mapNotNull { get(connection,it) }; return selected to if (more && selected.isNotEmpty()) encodeCursor(Instant.parse(selected.last().createdAt), selected.last().id) else null }
    private fun latestReturn(connection: Connection, orderId: String): ReturnResponse? = connection.prepareStatement("SELECT id FROM order_returns WHERE order_id=? ORDER BY created_at DESC LIMIT 1").use { statement -> statement.setString(1, orderId); statement.executeQuery().use { if (it.next()) returnById(connection, it.getString(1)) else null } }
    private fun returnById(connection: Connection, returnId: String): ReturnResponse? = connection.prepareStatement("SELECT r.*,i.variant_id,i.quantity FROM order_returns r LEFT JOIN order_return_items i ON i.return_id=r.id WHERE r.id=? ORDER BY i.variant_id").use { statement -> statement.setString(1, returnId); statement.executeQuery().use { result -> if (!result.next()) null else { val items=buildList { do { add(ReturnItemRequest(result.getString("variant_id"),result.getInt("quantity"))) } while(result.next()) }; ReturnResponse(result.getString("id"),result.getString("order_id"),result.getString("status"),result.getString("reason"),items,result.getTimestamp("created_at").toInstant().toString()) } } }
    private fun get(connection: Connection, id: String, userId: String? = null, lock: Boolean = false): OrderResponse? { val suffix=if(lock) " FOR UPDATE" else ""; val sql=if(userId==null) "SELECT * FROM orders WHERE id=?$suffix" else "SELECT * FROM orders WHERE id=? AND user_id=?$suffix"; return connection.prepareStatement(sql).use { statement -> statement.setString(1,id); if(userId!=null) statement.setString(2,userId); statement.executeQuery().use { result -> if(!result.next()) null else response(connection,result) } } }
    private fun response(connection: Connection, result: ResultSet): OrderResponse { val id=result.getString("id"); val items=connection.prepareStatement("SELECT * FROM order_items WHERE order_id=? ORDER BY id").use { statement -> statement.setString(1,id); statement.executeQuery().use { rows -> buildList { while(rows.next()) add(OrderItemSnapshot(rows.getString("product_id"),rows.getString("variant_id"),rows.getString("product_name"),rows.getString("sku"),rows.getString("seller_id"),rows.getInt("quantity"),rows.getLong("unit_price_minor"),rows.getLong("tax_minor"),rows.getLong("discount_minor"),rows.getLong("line_total_minor"),rows.getString("currency"),rows.getString("price_version"),json.decodeFromString(rows.getString("attributes_json")))) } } }; val addresses=connection.prepareStatement("SELECT * FROM order_addresses WHERE order_id=?").use { statement -> statement.setString(1,id); statement.executeQuery().use { rows -> buildMap { while(rows.next()) put(rows.getString("address_type"),AddressSnapshot(rows.getString("address_id"),rows.getString("recipient_name"),rows.getString("phone"),rows.getString("line1"),rows.getString("line2"),rows.getString("city"),rows.getString("state"),rows.getString("postal_code"),rows.getString("country"))) } } }; val promotion=connection.prepareStatement("SELECT * FROM order_promotion_snapshots WHERE order_id=?").use { statement -> statement.setString(1,id); statement.executeQuery().use { if(!it.next()) null else PromotionSnapshot(it.getString("promotion_id"),it.getString("coupon_code"),it.getLong("discount_minor"),json.decodeFromString(it.getString("allocation_json"))) } }; return OrderResponse(id,result.getString("user_id"),result.getString("checkout_id"),result.getString("reservation_id"),OrderStatus.valueOf(result.getString("status")),result.getLong("subtotal_minor"),result.getLong("item_discount_minor"),result.getLong("promotion_discount_minor"),result.getLong("shipping_minor"),result.getLong("tax_minor"),result.getLong("total_minor"),result.getString("currency"),items,addresses["SHIPPING"]!!,addresses["BILLING"]!!,promotion,result.getLong("version"),result.getTimestamp("created_at").toInstant().toString(),result.getTimestamp("updated_at").toInstant().toString()) }
    private fun address(connection: Connection, orderId: String, type: String, address: AddressSnapshot) = connection.prepareStatement("INSERT INTO order_addresses(order_id,address_type,address_id,recipient_name,phone,line1,line2,city,state,postal_code,country) VALUES (?,?,?,?,?,?,?,?,?,?,?)").use { statement -> statement.setString(1,orderId);statement.setString(2,type);statement.setString(3,address.addressId);statement.setString(4,address.recipientName);statement.setString(5,address.phone);statement.setString(6,address.line1);statement.setString(7,address.line2);statement.setString(8,address.city);statement.setString(9,address.state);statement.setString(10,address.postalCode);statement.setString(11,address.country);statement.executeUpdate() }
    private fun history(connection: Connection,id:String,from:OrderStatus?,to:OrderStatus,actor:String,reason:String?,now:Instant)=connection.prepareStatement("INSERT INTO order_status_history(id,order_id,from_status,to_status,actor_id,reason,created_at) VALUES (?,?,?,?,?,?,?)").use { s->s.setString(1,CommerceId.new("osh").value);s.setString(2,id);s.setString(3,from?.name);s.setString(4,to.name);s.setString(5,actor);s.setString(6,reason);s.setTimestamp(7,now.timestamp());s.executeUpdate() }
    private fun outbox(connection: Connection,response: Any,type:String,correlation:String,now:Instant)=connection.prepareStatement("INSERT INTO order_outbox_events(id,aggregate_id,event_type,occurred_at,correlation_id,payload_json) VALUES (?,?,?,?,?,?::jsonb)").use { s->s.setString(1,newOutboxId());s.setString(2,when(response){is OrderResponse->response.id;is ReturnResponse->response.orderId;else->"unknown"});s.setString(3,type);s.setTimestamp(4,now.timestamp());s.setString(5,correlation);s.setString(6,when(response){is OrderResponse->json.encodeToString(response);is ReturnResponse->json.encodeToString(response);else->"{}"});s.executeUpdate() }
    private fun eventType(status: OrderStatus)=when(status){OrderStatus.PAID->"OrderPaid";OrderStatus.CONFIRMED->"OrderConfirmed";OrderStatus.PROCESSING->"OrderProcessing";OrderStatus.SHIPPED->"OrderShipped";OrderStatus.OUT_FOR_DELIVERY->"OrderOutForDelivery";OrderStatus.DELIVERED->"OrderDelivered";OrderStatus.CANCELLED->"OrderCancelled";OrderStatus.CANCEL_REQUESTED->"OrderCancellationRequested";OrderStatus.RETURN_REQUESTED->"OrderReturnRequested";OrderStatus.REFUNDED->"OrderRefunded";else->"OrderStatusChanged"}
    override fun unpublished(limit: Int): List<ServiceOutboxRecord> = withConnection { c->c.prepareStatement("SELECT id,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json::text FROM order_outbox_events WHERE published_at IS NULL ORDER BY occurred_at LIMIT ?").use{s->s.setInt(1,limit);s.executeQuery().use{r->buildList{while(r.next())add(ServiceOutboxRecord(r.getString(1),"Order",r.getString(2),r.getString(3),r.getInt(4),r.getTimestamp(5).toInstant(),r.getString(6),r.getString(7)))}}}}
    override fun markPublished(ids:List<String>,publishedAt:Instant){if(ids.isEmpty())return;transaction{c->c.prepareStatement("UPDATE order_outbox_events SET published_at=? WHERE id=ANY(?)").use{s->s.setTimestamp(1,publishedAt.timestamp());s.setArray(2,c.createArrayOf("varchar",ids.toTypedArray()));s.executeUpdate()}}}
    private fun decodeCursor(v: String): Pair<Instant, String> = try{val p=String(Base64.getUrlDecoder().decode(v)).split('|',limit=2);Instant.parse(p[0]) to p[1]}catch(_:Exception){throw ApiException(ErrorCode.VALIDATION_ERROR,"Cursor is invalid.",400)}
    private fun encodeCursor(t:Instant,id:String)=Base64.getUrlEncoder().withoutPadding().encodeToString("$t|$id".toByteArray())
    private fun sha256(v:String)=MessageDigest.getInstance("SHA-256").digest(v.toByteArray()).joinToString(""){ "%02x".format(it) }
    private fun <T>withConnection(block:(Connection)->T):T=dataSource.connection.use(block)
    private fun <T>transaction(block:(Connection)->T):T=dataSource.connection.use{c->c.autoCommit=false;try{block(c).also{c.commit()}}catch(e:Throwable){c.rollback();throw e}}
}
private fun Instant.timestamp()=Timestamp.from(this)
