package com.ecommerce.inventory

import com.ecommerce.platform.common.CommerceId
import com.ecommerce.platform.error.ApiException
import com.ecommerce.platform.error.ErrorCode
import com.ecommerce.platform.service.ServiceOutboxRecord
import com.ecommerce.platform.service.ServiceOutboxStore
import com.ecommerce.platform.service.newOutboxId
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.security.MessageDigest
import java.sql.Connection
import java.sql.ResultSet
import java.sql.SQLException
import java.sql.Timestamp
import java.time.Instant
import javax.sql.DataSource

@Serializable
data class ReservationInput(val reservationKey: String, val actorId: String, val cartId: String?, val orderId: String?, val items: List<ReservationItem>, val ttlSeconds: Long)

@Serializable
data class InventoryItemInput(val warehouseId: String, val warehouseCode: String?, val warehouseName: String?, val productId: String, val variantId: String, val onHand: Long, val lowStockThreshold: Long)

class InventoryRepository(private val dataSource: DataSource) : ServiceOutboxStore {
    private val json = Json { encodeDefaults = true; ignoreUnknownKeys = true }

    fun createItem(input: InventoryItemInput, actorId: String, correlationId: String): InventoryItem = transaction { connection ->
        if (input.onHand < 0 || input.lowStockThreshold < 0) throw ApiException(ErrorCode.VALIDATION_ERROR, "Inventory quantities cannot be negative.", 400)
        val now = Instant.now(); val warehouseId = input.warehouseId.ifBlank { CommerceId.new("wh").value }
        if (input.warehouseId.isBlank()) connection.prepareStatement("INSERT INTO inventory_warehouses (id,code,name,country,created_at,updated_at) VALUES (?,?,?,?,?,?)").use { statement -> statement.setString(1, warehouseId); statement.setString(2, input.warehouseCode ?: warehouseId); statement.setString(3, input.warehouseName ?: warehouseId); statement.setString(4, "IN"); statement.setTimestamp(5, now.timestamp()); statement.setTimestamp(6, now.timestamp()); statement.executeUpdate() }
        try { connection.prepareStatement("INSERT INTO inventory_items (id,warehouse_id,product_id,variant_id,on_hand,reserved,available,low_stock_threshold,created_at,updated_at) VALUES (?,?,?,?,?,0,?,?,?,?)").use { statement -> statement.setString(1, CommerceId.new("inv").value); statement.setString(2, warehouseId); statement.setString(3, input.productId); statement.setString(4, input.variantId); statement.setLong(5, input.onHand); statement.setLong(6, input.onHand); statement.setLong(7, input.lowStockThreshold); statement.setTimestamp(8, now.timestamp()); statement.setTimestamp(9, now.timestamp()); statement.executeUpdate() }; val item = findItem(connection, input.variantId, warehouseId)!!; movement(connection, item, "INITIAL_STOCK", input.onHand, actorId, item.id, now); outbox(connection, item, "InventoryAdjusted", correlationId, now); item } catch (error: Exception) { if (error is SQLException && error.sqlState == "23505") throw ApiException(ErrorCode.CONFLICT, "Inventory item already exists.", 409); throw error }
    }

    fun findItem(variantId: String, warehouseId: String): InventoryItem? = withConnection { connection -> findItem(connection, variantId, warehouseId) }
    fun findByVariant(variantId: String): List<InventoryItem> = withConnection { connection -> connection.prepareStatement("SELECT * FROM inventory_items WHERE variant_id=? ORDER BY warehouse_id").use { statement -> statement.setString(1, variantId); statement.executeQuery().use { result -> buildList { while (result.next()) add(result.item()) } } } }

    fun reserve(input: ReservationInput, correlationId: String): Reservation {
        if (input.reservationKey.isBlank() || input.items.isEmpty() || input.ttlSeconds !in 30..86_400) throw ApiException(ErrorCode.VALIDATION_ERROR, "Reservation request is invalid.", 400)
        input.items.forEach { validateQuantity(it.quantity) }
        val normalizedItems = input.items.groupBy { it.variantId to it.warehouseId }.map { (key, values) -> ReservationItem(key.first, key.second, values.sumOf { it.quantity }) }.sortedWith(compareBy({ it.variantId }, { it.warehouseId }))
        normalizedItems.forEach { validateQuantity(it.quantity) }
        val normalizedInput = input.copy(items = normalizedItems)
        val hash = requestHash(normalizedInput)
        return try { transaction { connection ->
            val prior = idempotency(connection, input.reservationKey)
            if (prior != null) { if (prior.first != hash) throw ApiException(ErrorCode.CONFLICT, "Idempotency key was reused with a different request.", 409); return@transaction get(connection, prior.second)!! }
            val now = Instant.now(); val reservationId = CommerceId.new("res").value
            connection.prepareStatement("INSERT INTO inventory_reservations (id,reservation_key,actor_id,cart_id,order_id,status,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,'ACTIVE',?,?,?)").use { statement -> statement.setString(1, reservationId); statement.setString(2, input.reservationKey); statement.setString(3, input.actorId); statement.setString(4, input.cartId); statement.setString(5, input.orderId); statement.setTimestamp(6, now.plusSeconds(input.ttlSeconds).timestamp()); statement.setTimestamp(7, now.timestamp()); statement.setTimestamp(8, now.timestamp()); statement.executeUpdate() }
            normalizedItems.forEach { item -> val updated = connection.prepareStatement("UPDATE inventory_items SET reserved=reserved+?,available=available-?,version=version+1,updated_at=? WHERE variant_id=? AND warehouse_id=? AND available >= ?").use { statement -> statement.setLong(1, item.quantity); statement.setLong(2, item.quantity); statement.setTimestamp(3, now.timestamp()); statement.setString(4, item.variantId); statement.setString(5, item.warehouseId); statement.setLong(6, item.quantity); statement.executeUpdate() }; if (updated != 1) throw ApiException(ErrorCode.CONFLICT, "Insufficient inventory for variant ${item.variantId}.", 409); val inventory = findItem(connection, item.variantId, item.warehouseId)!!; connection.prepareStatement("INSERT INTO inventory_reservation_items (reservation_id,inventory_item_id,variant_id,warehouse_id,quantity) VALUES (?,?,?,?,?)").use { statement -> statement.setString(1, reservationId); statement.setString(2, inventory.id); statement.setString(3, item.variantId); statement.setString(4, item.warehouseId); statement.setLong(5, item.quantity); statement.executeUpdate() }; movement(connection, inventory, "RESERVE", 0, input.actorId, reservationId, now); maybeLowStock(connection, inventory.id, now, correlationId) }
            val reservation = get(connection, reservationId)!!; connection.prepareStatement("INSERT INTO inventory_idempotency (idempotency_key,request_hash,reservation_id,created_at) VALUES (?,?,?,?)").use { statement -> statement.setString(1, input.reservationKey); statement.setString(2, hash); statement.setString(3, reservationId); statement.setTimestamp(4, now.timestamp()); statement.executeUpdate() }; outbox(connection, reservation, "InventoryReserved", correlationId, now); reservation
        } } catch (error: Exception) { if (error is SQLException && error.sqlState == "23505") { withConnection { connection -> val prior = idempotency(connection, input.reservationKey) ?: throw error; if (prior.first != hash) throw ApiException(ErrorCode.CONFLICT, "Idempotency key was reused with a different request.", 409); get(connection, prior.second)!! } } else throw error }
    }

    fun getReservation(id: String): Reservation? = withConnection { connection -> get(connection, id) }
    fun release(id: String, actorId: String, correlationId: String, expired: Boolean = false): Reservation = transition(id, actorId, correlationId, if (expired) ReservationStatus.EXPIRED else ReservationStatus.RELEASED)
    fun commit(id: String, actorId: String, correlationId: String): Reservation = transition(id, actorId, correlationId, ReservationStatus.COMMITTED)

    private fun transition(id: String, actorId: String, correlationId: String, target: ReservationStatus): Reservation = transaction { connection ->
        val reservation = get(connection, id) ?: throw ApiException(ErrorCode.NOT_FOUND, "Reservation not found.", 404); if (reservation.actorId != actorId) throw ApiException(ErrorCode.FORBIDDEN, "You do not own this reservation.", 403)
        if (reservation.status == target) return@transaction reservation
        if (reservation.status != ReservationStatus.ACTIVE) throw ApiException(ErrorCode.CONFLICT, "Reservation cannot transition from ${reservation.status} to $target.", 409)
        val now = Instant.now(); val items = reservation.items
        items.forEach { item -> val sql = if (target == ReservationStatus.COMMITTED) "UPDATE inventory_items SET on_hand=on_hand-?,reserved=reserved-?,version=version+1,updated_at=? WHERE variant_id=? AND warehouse_id=? AND reserved >= ? AND on_hand >= ?" else "UPDATE inventory_items SET reserved=reserved-?,available=available+?,version=version+1,updated_at=? WHERE variant_id=? AND warehouse_id=? AND reserved >= ?"; val updated = connection.prepareStatement(sql).use { statement -> statement.setLong(1, item.quantity); statement.setLong(2, item.quantity); statement.setTimestamp(3, now.timestamp()); statement.setString(4, item.variantId); statement.setString(5, item.warehouseId); statement.setLong(6, item.quantity); if (target == ReservationStatus.COMMITTED) statement.setLong(7, item.quantity); statement.executeUpdate() }; if (updated != 1) throw ApiException(ErrorCode.CONFLICT, "Inventory state cannot complete this reservation.", 409); val inventory = findItem(connection, item.variantId, item.warehouseId)!!; movement(connection, inventory, target.name, 0, actorId, reservation.id, now); maybeLowStock(connection, inventory.id, now, correlationId) }
        connection.prepareStatement("UPDATE inventory_reservations SET status=?,updated_at=? WHERE id=?").use { statement -> statement.setString(1, target.name); statement.setTimestamp(2, now.timestamp()); statement.setString(3, id); statement.executeUpdate() }; val updated = get(connection, id)!!; outbox(connection, updated, "Inventory${target.name.replaceFirstChar { it.titlecase() }}", correlationId, now); updated
    }

    fun expireBatch(limit: Int, correlationId: String): Int { var count = 0; repeat(limit) { val expired = transaction { connection -> val id = connection.prepareStatement("SELECT id FROM inventory_reservations WHERE status='ACTIVE' AND expires_at <= ? ORDER BY expires_at FOR UPDATE SKIP LOCKED LIMIT 1").use { statement -> statement.setTimestamp(1, Instant.now().timestamp()); statement.executeQuery().use { if (it.next()) it.getString(1) else null } }; id }; if (expired != null) { runCatching { release(expired, getReservation(expired)!!.actorId, correlationId, true); count++ } } }; return count }

    fun adjust(itemId: String, delta: Long, type: AdjustmentType, reason: String, actorId: String, correlationId: String): InventoryItem = transaction { connection -> if (delta == 0L || reason.isBlank()) throw ApiException(ErrorCode.VALIDATION_ERROR, "Inventory adjustment is invalid.", 400); val before = lockItem(connection, itemId) ?: throw ApiException(ErrorCode.NOT_FOUND, "Inventory item not found.", 404); val newOnHand = before.onHand + delta; if (newOnHand < before.reserved) throw ApiException(ErrorCode.CONFLICT, "Adjustment would make available inventory negative.", 409); val now = Instant.now(); connection.prepareStatement("UPDATE inventory_items SET on_hand=?,available=?,version=version+1,updated_at=? WHERE id=?").use { statement -> statement.setLong(1, newOnHand); statement.setLong(2, newOnHand - before.reserved); statement.setTimestamp(3, now.timestamp()); statement.setString(4, itemId); statement.executeUpdate() }; val after = lockItem(connection, itemId)!!; connection.prepareStatement("INSERT INTO inventory_adjustments (id,inventory_item_id,adjustment_type,quantity_delta,reason,actor_id,created_at) VALUES (?,?,?,?,?,?,?)").use { statement -> statement.setString(1, CommerceId.new("adj").value); statement.setString(2, itemId); statement.setString(3, type.name); statement.setLong(4, delta); statement.setString(5, reason.take(1000)); statement.setString(6, actorId); statement.setTimestamp(7, now.timestamp()); statement.executeUpdate() }; movement(connection, after, type.name, delta, actorId, itemId, now); maybeLowStock(connection, itemId, now, correlationId); outbox(connection, after, "InventoryAdjusted", correlationId, now); after }

    fun movements(variantId: String, limit: Int): List<InventoryMovement> = withConnection { connection -> connection.prepareStatement("SELECT m.id,m.movement_type,m.quantity_delta,m.on_hand_after,m.reserved_after,m.available_after,m.reference_id,m.actor_id,m.created_at FROM inventory_movements m JOIN inventory_items i ON i.id=m.inventory_item_id WHERE i.variant_id=? ORDER BY m.created_at DESC LIMIT ?").use { statement -> statement.setString(1, variantId); statement.setInt(2, limit.coerceIn(1, 200)); statement.executeQuery().use { result -> buildList { while (result.next()) add(InventoryMovement(result.getString(1), result.getString(2), result.getLong(3), result.getLong(4), result.getLong(5), result.getLong(6), result.getString(7), result.getString(8), result.getTimestamp(9).toInstant().toString())) } } } }

    private fun maybeLowStock(connection: Connection, itemId: String, now: Instant, correlationId: String) {
        val item = lockItem(connection, itemId) ?: return
        if (item.available <= item.lowStockThreshold && item.lowStockThreshold > 0 && !lowNotified(connection, itemId)) {
            connection.prepareStatement("UPDATE inventory_items SET low_stock_notified=TRUE WHERE id=?").use { statement -> statement.setString(1, itemId); statement.executeUpdate() }
            inventoryEvent(connection, item, "InventoryLowStock", correlationId, now)
        } else if (item.available > item.lowStockThreshold && lowNotified(connection, itemId)) {
            connection.prepareStatement("UPDATE inventory_items SET low_stock_notified=FALSE WHERE id=?").use { statement -> statement.setString(1, itemId); statement.executeUpdate() }
        }
        if (item.available == 0L && !outOfStockNotified(connection, itemId)) {
            connection.prepareStatement("UPDATE inventory_items SET out_of_stock_notified=TRUE WHERE id=?").use { statement -> statement.setString(1, itemId); statement.executeUpdate() }
            inventoryEvent(connection, item, "InventoryOutOfStock", correlationId, now)
        } else if (item.available > 0L && outOfStockNotified(connection, itemId)) {
            connection.prepareStatement("UPDATE inventory_items SET out_of_stock_notified=FALSE WHERE id=?").use { statement -> statement.setString(1, itemId); statement.executeUpdate() }
        }
    }
    private fun inventoryEvent(connection: Connection, item: InventoryItem, type: String, correlationId: String, now: Instant) = connection.prepareStatement("INSERT INTO inventory_outbox_events (id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json) VALUES (?,?,?,?,1,?,?,?::jsonb)").use { statement -> statement.setString(1, newOutboxId()); statement.setString(2, "InventoryItem"); statement.setString(3, item.id); statement.setString(4, type); statement.setTimestamp(5, now.timestamp()); statement.setString(6, correlationId); statement.setString(7, json.encodeToString(InventoryEventPayload(item.id, item.variantId, item.warehouseId, item.available, item.lowStockThreshold))); statement.executeUpdate() }
    private fun lowNotified(connection: Connection, id: String): Boolean = connection.prepareStatement("SELECT low_stock_notified FROM inventory_items WHERE id=?").use { statement -> statement.setString(1, id); statement.executeQuery().use { it.next() && it.getBoolean(1) } }
    private fun outOfStockNotified(connection: Connection, id: String): Boolean = connection.prepareStatement("SELECT out_of_stock_notified FROM inventory_items WHERE id=?").use { statement -> statement.setString(1, id); statement.executeQuery().use { it.next() && it.getBoolean(1) } }
    private fun movement(connection: Connection, item: InventoryItem, type: String, delta: Long, actorId: String, reference: String?, now: Instant) = connection.prepareStatement("INSERT INTO inventory_movements (id,inventory_item_id,movement_type,quantity_delta,on_hand_after,reserved_after,available_after,reference_id,actor_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").use { statement -> statement.setString(1, CommerceId.new("mov").value); statement.setString(2, item.id); statement.setString(3, type); statement.setLong(4, delta); statement.setLong(5, item.onHand); statement.setLong(6, item.reserved); statement.setLong(7, item.available); statement.setString(8, reference); statement.setString(9, actorId); statement.setTimestamp(10, now.timestamp()); statement.executeUpdate() }
    private fun outbox(connection: Connection, reservation: Reservation, type: String, correlationId: String, now: Instant) = connection.prepareStatement("INSERT INTO inventory_outbox_events (id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json) VALUES (?,?,?,?,1,?,?,?::jsonb)").use { statement -> statement.setString(1, newOutboxId()); statement.setString(2, "Reservation"); statement.setString(3, reservation.id); statement.setString(4, type); statement.setTimestamp(5, now.timestamp()); statement.setString(6, correlationId); statement.setString(7, json.encodeToString(ReservationEventPayload(reservation.id, reservation.status.name, reservation.items))); statement.executeUpdate() }
    private fun outbox(connection: Connection, item: InventoryItem, type: String, correlationId: String, now: Instant) = connection.prepareStatement("INSERT INTO inventory_outbox_events (id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json) VALUES (?,?,?,?,1,?,?,?::jsonb)").use { statement -> statement.setString(1, newOutboxId()); statement.setString(2, "InventoryItem"); statement.setString(3, item.id); statement.setString(4, type); statement.setTimestamp(5, now.timestamp()); statement.setString(6, correlationId); statement.setString(7, json.encodeToString(InventoryEventPayload(item.id, item.variantId, item.warehouseId, item.available, item.lowStockThreshold))); statement.executeUpdate() }
    private fun idempotency(connection: Connection, key: String): Pair<String, String>? = connection.prepareStatement("SELECT request_hash,reservation_id FROM inventory_idempotency WHERE idempotency_key=?").use { statement -> statement.setString(1, key); statement.executeQuery().use { if (it.next()) it.getString(1) to it.getString(2) else null } }
    private fun requestHash(input: ReservationInput): String = MessageDigest.getInstance("SHA-256").digest(json.encodeToString(input).toByteArray()).joinToString("") { "%02x".format(it) }
    private fun get(connection: Connection, id: String): Reservation? = connection.prepareStatement("SELECT * FROM inventory_reservations WHERE id=?").use { statement -> statement.setString(1, id); statement.executeQuery().use { result -> if (!result.next()) null else { val items = connection.prepareStatement("SELECT variant_id,warehouse_id,quantity FROM inventory_reservation_items WHERE reservation_id=? ORDER BY variant_id,warehouse_id").use { child -> child.setString(1, id); child.executeQuery().use { rows -> buildList { while (rows.next()) add(ReservationItem(rows.getString(1), rows.getString(2), rows.getLong(3))) } } }; Reservation(result.getString("id"), result.getString("reservation_key"), result.getString("actor_id"), result.getString("cart_id"), result.getString("order_id"), ReservationStatus.valueOf(result.getString("status")), result.getTimestamp("expires_at").toInstant().toString(), result.getTimestamp("created_at").toInstant().toString(), result.getTimestamp("updated_at").toInstant().toString(), items) } } }
    private fun findItem(connection: Connection, variantId: String, warehouseId: String): InventoryItem? = connection.prepareStatement("SELECT * FROM inventory_items WHERE variant_id=? AND warehouse_id=?").use { statement -> statement.setString(1, variantId); statement.setString(2, warehouseId); statement.executeQuery().use { result -> if (result.next()) result.item() else null } }
    private fun lockItem(connection: Connection, id: String): InventoryItem? = connection.prepareStatement("SELECT * FROM inventory_items WHERE id=? FOR UPDATE").use { statement -> statement.setString(1, id); statement.executeQuery().use { result -> if (result.next()) result.item() else null } }
    override fun unpublished(limit: Int): List<ServiceOutboxRecord> = withConnection { connection -> connection.prepareStatement("SELECT id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json::text FROM inventory_outbox_events WHERE published_at IS NULL ORDER BY occurred_at LIMIT ?").use { statement -> statement.setInt(1, limit); statement.executeQuery().use { result -> buildList { while (result.next()) add(ServiceOutboxRecord(result.getString(1), result.getString(2), result.getString(3), result.getString(4), result.getInt(5), result.getTimestamp(6).toInstant(), result.getString(7), result.getString(8))) } } } }
    override fun markPublished(ids: List<String>, publishedAt: Instant) { transaction { connection -> connection.prepareStatement("UPDATE inventory_outbox_events SET published_at=? WHERE id=ANY(?)").use { statement -> statement.setTimestamp(1, publishedAt.timestamp()); statement.setArray(2, connection.createArrayOf("varchar", ids.toTypedArray())); statement.executeUpdate() } } }
    private fun <T> withConnection(block: (Connection) -> T): T = dataSource.connection.use(block)
    private fun <T> transaction(block: (Connection) -> T): T = dataSource.connection.use { connection -> connection.autoCommit = false; try { block(connection).also { connection.commit() } } catch (error: Throwable) { connection.rollback(); throw error } }
}

private fun ResultSet.item(): InventoryItem = InventoryItem(getString("id"), getString("warehouse_id"), getString("product_id"), getString("variant_id"), getLong("on_hand"), getLong("reserved"), getLong("available"), getLong("low_stock_threshold"), getLong("version"), getTimestamp("updated_at").toInstant().toString())
private fun Instant.timestamp(): Timestamp = Timestamp.from(this)
