package com.ecommerce.flags

import com.ecommerce.platform.error.ApiException
import com.ecommerce.platform.error.ErrorCode
import com.ecommerce.platform.service.ServiceOutboxRecord
import com.ecommerce.platform.service.ServiceOutboxStore
import com.ecommerce.platform.service.newOutboxId
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.sql.Connection
import java.sql.Timestamp
import java.time.Instant
import javax.sql.DataSource

class FlagRepository(private val ds:DataSource,private val json:Json):ServiceOutboxStore {
    fun list():List<FeatureFlagResponse > =ds.connection.use{c->c.prepareStatement("SELECT * FROM feature_flags ORDER BY key").use{s->s.executeQuery().use{r->buildList{while(r.next())add(r.flag())}}}}
    fun get(key:String):FeatureFlagResponse?=ds.connection.use{c->c.prepareStatement("SELECT * FROM feature_flags WHERE key=?").use{s->s.setString(1,key);s.executeQuery().use{if(it.next())it.flag()else null}}}
    fun save(actor:String,r:FeatureFlagRequest,correlation:String):FeatureFlagResponse=tx{c->validate(r);val old=get(c,r.key);if(old!=null&&r.expectedVersion!=old.version)throw ApiException(ErrorCode.CONFLICT,"Feature flag version conflict.",409);val next=(old?.version?:0)+1;if(old==null)c.prepareStatement("INSERT INTO feature_flags(key,value_type,default_value,fail_safe_value,enabled,environment,rollout_bps,rules_json,version,updated_by) VALUES (?,?,?::jsonb,?::jsonb,?,?,?,?::jsonb,?,?)").use{s->bind(s,r,next,actor);s.executeUpdate()}else c.prepareStatement("UPDATE feature_flags SET value_type=?,default_value=?::jsonb,fail_safe_value=?::jsonb,enabled=?,environment=?,rollout_bps=?,rules_json=?::jsonb,version=?,updated_by=?,updated_at=now() WHERE key=? AND version=?").use{s->s.setString(1,r.valueType.name);s.setString(2,r.defaultValue);s.setString(3,r.failSafeValue);s.setBoolean(4,r.enabled);s.setString(5,r.environment);s.setInt(6,r.rolloutBps);s.setString(7,r.rulesJson);s.setLong(8,next);s.setString(9,actor);s.setString(10,r.key);s.setLong(11,old.version);if(s.executeUpdate()==0)throw ApiException(ErrorCode.CONFLICT,"Feature flag version conflict.",409)};c.prepareStatement("INSERT INTO feature_flag_versions(flag_key,version,value_json,rules_json,changed_by) VALUES (?,?,?::jsonb,?::jsonb,?)").use{s->s.setString(1,r.key);s.setLong(2,next);s.setString(3,r.defaultValue);s.setString(4,r.rulesJson);s.setString(5,actor);s.executeUpdate()};c.prepareStatement("INSERT INTO feature_flag_audit(flag_key,action,actor_id,before_json,after_json) VALUES (?,?,?,?,?::jsonb)").use{s->s.setString(1,r.key);s.setString(2,if(old==null)"CREATED" else "UPDATED");s.setString(3,actor);s.setString(4,old?.let{json.encodeToString(it)});s.setString(5,json.encodeToString(r));s.executeUpdate()};val result=get(c,r.key)!!;outbox(c,r.key,"FeatureFlagChanged",correlation,result);result}
    fun delete(actor:String,key:String,correlation:String)=tx{c->val old=get(c,key)?:throw ApiException(ErrorCode.NOT_FOUND,"Feature flag not found.",404);c.prepareStatement("DELETE FROM feature_flags WHERE key=?").use{s->s.setString(1,key);s.executeUpdate()};c.prepareStatement("INSERT INTO feature_flag_audit(flag_key,action,actor_id,before_json) VALUES (?,?,?,?::jsonb)").use{s->s.setString(1,key);s.setString(2,"DELETED");s.setString(3,actor);s.setString(4,json.encodeToString(old));s.executeUpdate()};outbox(c,key,"FeatureFlagChanged",correlation,old);Unit}
    fun evaluate(r:EvaluationRequest):EvaluationResponse{val flag=get(r.key)?:return EvaluationResponse(r.key,r.fallbackValue,false,0,"safe-default");if(flag.environment!=r.environment)return EvaluationResponse(flag.key,flag.failSafeValue,false,flag.version,"environment-default");if(!flag.enabled)return EvaluationResponse(flag.key,flag.failSafeValue,false,flag.version,"disabled");if(!matches(flag.rulesJson,r))return EvaluationResponse(flag.key,flag.failSafeValue,false,flag.version,"target-default");val bucket=deterministicBucket(r.userId?:r.sellerId?:"anonymous:${r.platform.orEmpty()}",flag.key);return if(bucket<flag.rolloutBps)EvaluationResponse(flag.key,flag.defaultValue,true,flag.version,"rollout")else EvaluationResponse(flag.key,flag.failSafeValue,false,flag.version,"rollout-excluded")}
    override fun unpublished(limit:Int):List<ServiceOutboxRecord > =ds.connection.use{c->c.prepareStatement("SELECT id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json::text FROM feature_flag_outbox_events WHERE published_at IS NULL ORDER BY occurred_at LIMIT ?").use{s->s.setInt(1,limit);s.executeQuery().use{r->buildList{while(r.next())add(ServiceOutboxRecord(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getInt(5),r.getTimestamp(6).toInstant(),r.getString(7),r.getString(8)))}}}}
    override fun markPublished(ids:List<String>,publishedAt:Instant){if(ids.isEmpty())return;ds.connection.use{c->c.prepareStatement("UPDATE feature_flag_outbox_events SET published_at=? WHERE id=ANY(?)").use{s->s.setTimestamp(1,Timestamp.from(publishedAt));s.setArray(2,c.createArrayOf("varchar",ids.toTypedArray()));s.executeUpdate()}}}
    private fun matches(raw:String,r:EvaluationRequest):Boolean=runCatching{
        val o=json.parseToJsonElement(raw).jsonObject
        fun matchesList(name:String,value:String?):Boolean{
            val configured=o[name]?.jsonPrimitive?.content ?: return true
            return value!=null&&value in configured.split(',').map(String::trim).filter(String::isNotBlank)
        }
        val minimumVersion=o["minimumVersion"]?.jsonPrimitive?.content
        matchesList("platform",r.platform)&&matchesList("country",r.country)&&matchesList("sellerId",r.sellerId)&&matchesList("userIds",r.userId)&&matchesList("appVersion",r.appVersion)&&(minimumVersion==null||compareVersions(r.appVersion,minimumVersion)>=0)
    }.getOrDefault(false)
    private fun compareVersions(actual:String?,minimum:String):Int{if(actual==null)return -1;val a=actual.split('.', '-', '_').map{it.toIntOrNull()?:0};val b=minimum.split('.', '-', '_').map{it.toIntOrNull()?:0};for(i in 0 until maxOf(a.size,b.size)){val result=(a.getOrElse(i){0}).compareTo(b.getOrElse(i){0});if(result!=0)return result};return 0}
    private fun get(c:Connection,key:String):FeatureFlagResponse?=c.prepareStatement("SELECT * FROM feature_flags WHERE key=?").use{s->s.setString(1,key);s.executeQuery().use{if(it.next())it.flag()else null}}
    private fun validate(r:FeatureFlagRequest){if(!r.key.matches(Regex("[a-z0-9_.-]+"))||r.rolloutBps !in 0..10000)throw ApiException(ErrorCode.VALIDATION_ERROR,"Feature flag is invalid.",400);runCatching{json.parseToJsonElement(r.defaultValue);json.parseToJsonElement(r.failSafeValue);json.parseToJsonElement(r.rulesJson)}.getOrElse{throw ApiException(ErrorCode.VALIDATION_ERROR,"Feature flag values must be valid JSON.",400)}}
    private fun bind(s:java.sql.PreparedStatement,r:FeatureFlagRequest,v:Long,actor:String){s.setString(1,r.key);s.setString(2,r.valueType.name);s.setString(3,r.defaultValue);s.setString(4,r.failSafeValue);s.setBoolean(5,r.enabled);s.setString(6,r.environment);s.setInt(7,r.rolloutBps);s.setString(8,r.rulesJson);s.setLong(9,v);s.setString(10,actor)}
    private fun java.sql.ResultSet.flag()=FeatureFlagResponse(getString("key"),FlagValueType.valueOf(getString("value_type")),getString("default_value"),getString("fail_safe_value"),getBoolean("enabled"),getString("environment"),getInt("rollout_bps"),getString("rules_json"),getLong("version"),getString("updated_by"),getTimestamp("updated_at").toInstant().toString())
    private fun outbox(c:Connection,key:String,type:String,correlation:String,response:FeatureFlagResponse){c.prepareStatement("INSERT INTO feature_flag_outbox_events(id,aggregate_type,aggregate_id,event_type,occurred_at,correlation_id,payload_json) VALUES (?,?,?,?,?,?,?::jsonb)").use{s->s.setString(1,newOutboxId());s.setString(2,"FeatureFlag");s.setString(3,key);s.setString(4,type);s.setTimestamp(5,Timestamp.from(Instant.now()));s.setString(6,correlation);s.setString(7,json.encodeToString(response));s.executeUpdate()}}
    private fun <T>tx(b:(Connection)->T):T=ds.connection.use{c->c.autoCommit=false;try{b(c).also{c.commit()}}catch(e:Throwable){c.rollback();throw e}}
}
