package com.ecommerce.shipping

import com.ecommerce.platform.common.CommerceId
import com.ecommerce.platform.error.ApiException
import com.ecommerce.platform.error.ErrorCode
import com.ecommerce.platform.service.ServiceOutboxRecord
import com.ecommerce.platform.service.ServiceOutboxStore
import com.ecommerce.platform.service.newOutboxId
import kotlinx.serialization.json.Json
import java.security.MessageDigest
import java.sql.Connection
import java.sql.ResultSet
import java.sql.Timestamp
import java.time.Instant
import javax.sql.DataSource

class ShippingRepository(private val dataSource:DataSource,private val provider:ShippingProvider):ServiceOutboxStore{
    private val json=Json{encodeDefaults=true;explicitNulls=false;ignoreUnknownKeys=true}
    fun quote(userId:String,request:ShippingQuoteRequest):ShippingQuote{if(request.items.isEmpty()||request.currency !in setOf("INR","USD","EUR","GBP"))throw ApiException(ErrorCode.VALIDATION_ERROR,"Shipping quote is invalid.",400);val result=provider.quote(request);withConnection{c->c.prepareStatement("INSERT INTO shipping_quotes(id,user_id,method,amount_minor,currency,request_hash,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?)").use{s->s.setString(1,result.quoteId);s.setString(2,userId);s.setString(3,result.method.name);s.setLong(4,result.amountMinor);s.setString(5,result.currency);s.setString(6,sha(json.encodeToString(request)));s.setTimestamp(7,Timestamp.from(Instant.parse(result.expiresAt)));s.setTimestamp(8,Timestamp.from(Instant.now()));s.executeUpdate()}};return result}
    fun create(request:ShipmentCreateRequest,key:String,correlation:String):ShipmentResponse{if(request.orderId.isBlank()||request.userId.isBlank()||request.items.isEmpty()||request.amountMinor<0)throw ApiException(ErrorCode.VALIDATION_ERROR,"Shipment request is invalid.",400);val hash=sha(json.encodeToString(request));val existing=withConnection{c->c.prepareStatement("SELECT request_hash,id FROM shipments WHERE user_id=? AND idempotency_key=?").use{s->s.setString(1,request.userId);s.setString(2,key);s.executeQuery().use{r->if(r.next()){if(r.getString(1)!=hash)throw ApiException(ErrorCode.CONFLICT,"Shipment idempotency key was reused.",409);get(c,r.getString(2))}else null}}};if(existing!=null)return existing;val id=CommerceId.new("shp").value;withConnection{c->c.prepareStatement("INSERT INTO shipments(id,order_id,user_id,provider,status,method,amount_minor,currency,idempotency_key,request_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").use{s->val now=Timestamp.from(Instant.now());s.setString(1,id);s.setString(2,request.orderId);s.setString(3,request.userId);s.setString(4,provider.name);s.setString(5,ShipmentStatus.LABEL_PENDING.name);s.setString(6,request.method.name);s.setLong(7,request.amountMinor);s.setString(8,request.currency);s.setString(9,key);s.setString(10,hash);s.setTimestamp(11,now);s.setTimestamp(12,now);s.executeUpdate()};c.prepareStatement("INSERT INTO shipment_addresses(shipment_id,address_json) VALUES(?,?::jsonb)").use{s->s.setString(1,id);s.setString(2,json.encodeToString(request.address));s.executeUpdate()};request.items.forEach{item->c.prepareStatement("INSERT INTO shipment_items(shipment_id,variant_id,quantity) VALUES(?,?,?)").use{s->s.setString(1,id);s.setString(2,item.variantId);s.setInt(3,item.quantity);s.executeUpdate()}}};val external=provider.create(request);return transaction{c->update(c,id,external,correlation);get(c,id)!!}}
    fun getOwned(userId:String,id:String)=withConnection{get(it,id,userId)}
    fun getInternal(id:String)=withConnection{get(it,id)}
    fun tracking(request:TrackingWebhook,correlation:String):ShipmentResponse=transaction{c->val existing=c.prepareStatement("SELECT id FROM shipment_tracking_events WHERE provider_event_id=?").use{s->s.setString(1,request.providerEventId);s.executeQuery().use{r->if(r.next())r.getString(1)else null}};val current=getByProvider(c,request.providerShipmentId,true)?:throw ApiException(ErrorCode.NOT_FOUND,"Shipment not found.",404);if(existing==null){c.prepareStatement("INSERT INTO shipment_tracking_events(id,shipment_id,status,provider_event_id,payload_json,occurred_at) VALUES(?,?,?,?,?::jsonb,?)").use{s->s.setString(1,CommerceId.new("track").value);s.setString(2,current.id);s.setString(3,request.status.name);s.setString(4,request.providerEventId);s.setString(5,json.encodeToString(request.payload));s.setTimestamp(6,Timestamp.from(Instant.now()));s.executeUpdate()};update(c,current.id,ProviderShipment(request.providerShipmentId,request.status,request.trackingNumber,current.carrier),correlation)};get(c,current.id)!!}
    private fun update(c:Connection,id:String,external:ProviderShipment,correlation:String){val current=get(c,id,null,true)?:throw ApiException(ErrorCode.NOT_FOUND,"Shipment not found.",404);try{assertShipmentTransition(current.status,external.status)}catch(_:IllegalStateException){throw ApiException(ErrorCode.CONFLICT,"Shipment cannot transition from ${current.status} to ${external.status}.",409)};val now=Instant.now();c.prepareStatement("UPDATE shipments SET status=?,provider_shipment_id=COALESCE(?,provider_shipment_id),tracking_number=COALESCE(?,tracking_number),carrier=COALESCE(?,carrier),updated_at=? WHERE id=?").use{s->s.setString(1,external.status.name);s.setString(2,external.providerShipmentId);s.setString(3,external.trackingNumber);s.setString(4,external.carrier);s.setTimestamp(5,Timestamp.from(now));s.setString(6,id);s.executeUpdate()};outbox(c,get(c,id)!!,if(external.status==ShipmentStatus.DELIVERED)"ShipmentDelivered" else "ShipmentStatusChanged",correlation,now)}
    private fun getByProvider(c:Connection,id:String,lock:Boolean)=get(c,id,null,lock,"provider_shipment_id")
    private fun get(c:Connection,id:String,userId:String?=null,lock:Boolean=false,column:String="id"):ShipmentResponse?{val suffix=if(lock)" FOR UPDATE" else"";val sql=if(userId==null)"SELECT * FROM shipments WHERE $column=?$suffix" else"SELECT * FROM shipments WHERE $column=? AND user_id=?$suffix";return c.prepareStatement(sql).use{s->s.setString(1,id);if(userId!=null)s.setString(2,userId);s.executeQuery().use{r->if(r.next())response(r)else null}}}
    private fun response(r:ResultSet)=ShipmentResponse(r.getString("id"),r.getString("order_id"),r.getString("user_id"),r.getString("provider"),r.getString("provider_shipment_id"),ShipmentStatus.valueOf(r.getString("status")),ShippingMethod.valueOf(r.getString("method")),r.getString("tracking_number"),r.getString("carrier"),r.getLong("amount_minor"),r.getString("currency"),r.getTimestamp("created_at").toInstant().toString(),r.getTimestamp("updated_at").toInstant().toString())
    private fun outbox(c:Connection,value:ShipmentResponse,type:String,correlation:String,now:Instant)=c.prepareStatement("INSERT INTO shipping_outbox_events(id,aggregate_id,event_type,occurred_at,correlation_id,payload_json) VALUES(?,?,?,?,?,?::jsonb)").use{s->s.setString(1,newOutboxId());s.setString(2,value.id);s.setString(3,type);s.setTimestamp(4,Timestamp.from(now));s.setString(5,correlation);s.setString(6,json.encodeToString(value));s.executeUpdate()}
    override fun unpublished(limit:Int):List<ServiceOutboxRecord> = withConnection{c->c.prepareStatement("SELECT id,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json::text FROM shipping_outbox_events WHERE published_at IS NULL ORDER BY occurred_at LIMIT ?").use{s->s.setInt(1,limit);s.executeQuery().use{r->buildList{while(r.next())add(ServiceOutboxRecord(r.getString(1),"Shipping",r.getString(2),r.getString(3),r.getInt(4),r.getTimestamp(5).toInstant(),r.getString(6),r.getString(7)))}}}}
    override fun markPublished(ids:List<String>,publishedAt:Instant){if(ids.isEmpty())return;transaction{c->c.prepareStatement("UPDATE shipping_outbox_events SET published_at=? WHERE id=ANY(?)").use{s->s.setTimestamp(1,Timestamp.from(publishedAt));s.setArray(2,c.createArrayOf("varchar",ids.toTypedArray()));s.executeUpdate()}}}
    private fun sha(v:String)=MessageDigest.getInstance("SHA-256").digest(v.toByteArray()).joinToString(""){ "%02x".format(it) }
    private fun <T>withConnection(block:(Connection)->T):T=dataSource.connection.use(block)
    private fun <T>transaction(block:(Connection)->T):T=dataSource.connection.use{c->c.autoCommit=false;try{block(c).also{c.commit()}}catch(e:Throwable){c.rollback();throw e}}
}
