ktor { deployment { port = 8095; port = ${?CHECKOUT_PORT}; shutdownGracePeriod = 5s; shutdownTimeout = 15s }; application { modules = [ com.ecommerce.checkout.ApplicationKt.module ] } }
checkout {
    database { url = ${?CHECKOUT_DATABASE_URL}; username = ${?CHECKOUT_DATABASE_USERNAME}; password = ${?CHECKOUT_DATABASE_PASSWORD}; maximumPoolSize = 30; connectionTimeoutMillis = 2000 }
    jwt { issuer = "commerce-identity"; audience = "commerce-api"; keys = ${?JWT_KEYS} }
    kafka { bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}; topic = "checkout.events.v1"; tenantId = ${?IDENTITY_TENANT_ID} }
    cartBaseUrl = ${?CART_SERVICE_URL}
    pricingBaseUrl = ${?PRICING_SERVICE_URL}
    promotionBaseUrl = ${?PROMOTION_SERVICE_URL}
    inventoryBaseUrl = ${?INVENTORY_SERVICE_URL}
    identityBaseUrl = ${?IDENTITY_SERVICE_URL}
    catalogBaseUrl = ${?CATALOG_SERVICE_URL}
    shippingBaseUrl = ${?SHIPPING_SERVICE_URL}
    orderBaseUrl = ${?ORDER_SERVICE_URL}
    paymentBaseUrl = ${?PAYMENT_SERVICE_URL}
    warehouseId = ${?DEFAULT_WAREHOUSE_ID}
    internalToken = ${?INTERNAL_SERVICE_TOKEN}
}
