ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        shutdownGracePeriod = 2000
        shutdownTimeout = 5000
    }
    application {
        modules = [ com.ecommerce.gateway.ApplicationKt.module ]
    }
}

app {
    environment = "local"
    environment = ${?APP_ENV}
    allowedHosts = [ "localhost:3000", "localhost:8080" ]
}
