package com.ecommerce.pricing

import com.ecommerce.platform.common.CommerceId
import com.ecommerce.platform.error.ApiException
import com.ecommerce.platform.error.ErrorCode
import com.ecommerce.platform.service.ServiceOutboxRecord
import com.ecommerce.platform.service.ServiceOutboxStore
import com.ecommerce.platform.service.newOutboxId
import kotlinx.serialization.json.Json
import java.sql.Connection
import java.sql.ResultSet
import java.sql.SQLException
import java.sql.Timestamp
import java.time.Instant
import javax.sql.DataSource

data class PriceInput(val productId: String, val variantId: String?, val sellerId: String?, val currency: String, val region: String, val customerSegment: String, val baseMinor: Long, val saleMinor: Long?, val taxRateBps: Int, val effectiveFrom: Instant, val effectiveTo: Instant?)
data class QuoteItem(val productId: String, val variantId: String?, val quantity: Int)

class PricingRepository(private val dataSource: DataSource) : PricingStore, ServiceOutboxStore {
    private val json = Json { encodeDefaults = true }

    override fun current(productId: String, variantId: String?, currency: String, region: String, segment: String): Price? = current(productId, variantId, currency, region, segment, Instant.now())
    fun current(productId: String, variantId: String?, currency: String, region: String, segment: String, now: Instant): Price? = withConnection { connection ->
        connection.prepareStatement("SELECT * FROM prices WHERE product_id=? AND variant_id IS NOT DISTINCT FROM ? AND currency=? AND region=? AND customer_segment=? AND effective_from <= ? AND (effective_to IS NULL OR effective_to > ?) ORDER BY variant_id NULLS LAST, effective_from DESC, version DESC LIMIT 1").use { statement -> statement.setString(1, productId); statement.setString(2, variantId); statement.setString(3, currency); statement.setString(4, region); statement.setString(5, segment); statement.setTimestamp(6, now.timestamp()); statement.setTimestamp(7, now.timestamp()); statement.executeQuery().use { result -> if (result.next()) result.price() else null } }
    }

    override fun create(input: PriceInput, actorId: String, correlationId: String): Price = transaction { connection ->
        validate(input); val id = CommerceId.new("price").value; val now = Instant.now(); val price = insert(connection, id, input.copy(effectiveFrom = input.effectiveFrom), actorId, now, 1); snapshot(connection, price, actorId, now); outbox(connection, price, "PriceUpdated", correlationId, now); price
    }

    override fun update(id: String, input: PriceInput, actorId: String, correlationId: String): Price = transaction { connection ->
        validate(input); val existing = get(connection, id) ?: throw ApiException(ErrorCode.NOT_FOUND, "Price not found.", 404); val now = Instant.now(); snapshot(connection, existing, actorId, now); val updated = updateRow(connection, id, input, actorId, existing.version + 1, now); outbox(connection, updated, "PriceUpdated", correlationId, now); updated
    }

    override fun delete(id: String, actorId: String, correlationId: String) = transaction { connection ->
        val existing = get(connection, id) ?: throw ApiException(ErrorCode.NOT_FOUND, "Price not found.", 404); val now = Instant.now(); snapshot(connection, existing, actorId, now); connection.prepareStatement("UPDATE prices SET effective_to=COALESCE(effective_to,?),version=version+1,updated_at=? WHERE id=?").use { statement -> statement.setTimestamp(1, now.timestamp()); statement.setTimestamp(2, now.timestamp()); statement.setString(3, id); statement.executeUpdate() }; outbox(connection, existing, "PriceDeleted", correlationId, now) }

    override fun quote(items: List<QuoteItem>, currency: String, region: String, segment: String): PriceQuote { if (items.isEmpty() || items.any { it.quantity !in 1..1000 }) throw ApiException(ErrorCode.VALIDATION_ERROR, "Quote items and quantities are invalid.", 400); val lines = items.map { item -> val price = current(item.productId, item.variantId, currency, region, segment) ?: throw ApiException(ErrorCode.NOT_FOUND, "Price not found for ${item.productId}.", 404); val subtotal = Math.multiplyExact(price.unitMinor, item.quantity.toLong()); val tax = calculateTaxMinor(subtotal, price.taxRateBps); QuoteLine(item.productId, item.variantId, item.quantity, price.unitMinor, subtotal, tax) }; val subtotal = lines.sumOf { it.lineSubtotalMinor }; val tax = lines.sumOf { it.lineTaxMinor }; val versions = lines.mapNotNull { current(it.productId, it.variantId, currency, region, segment)?.let { price -> "${price.id}:${price.version}" } }.joinToString(","); return PriceQuote(lines, subtotal, 0, tax, 0, subtotal + tax, currency, versions) }

    private fun validate(input: PriceInput) { if (!input.currency.matches(Regex("[A-Z]{3}")) || input.baseMinor < 0 || input.saleMinor != null && (input.saleMinor < 0 || input.saleMinor > input.baseMinor) || input.taxRateBps !in 0..10000 || input.effectiveTo != null && input.effectiveTo <= input.effectiveFrom) throw ApiException(ErrorCode.VALIDATION_ERROR, "Price values are invalid.", 400) }
    private fun insert(connection: Connection, id: String, input: PriceInput, actorId: String, now: Instant, version: Long): Price { connection.prepareStatement("INSERT INTO prices (id,product_id,variant_id,seller_id,currency,region,customer_segment,base_minor,sale_minor,tax_rate_bps,effective_from,effective_to,version,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").use { statement -> statement.setString(1, id); statement.setString(2, input.productId); statement.setString(3, input.variantId); statement.setString(4, input.sellerId); statement.setString(5, input.currency); statement.setString(6, input.region); statement.setString(7, input.customerSegment); statement.setLong(8, input.baseMinor); if (input.saleMinor == null) statement.setNull(9, java.sql.Types.BIGINT) else statement.setLong(9, input.saleMinor); statement.setInt(10, input.taxRateBps); statement.setTimestamp(11, input.effectiveFrom.timestamp()); statement.setTimestamp(12, input.effectiveTo?.timestamp()); statement.setLong(13, version); statement.setString(14, actorId); statement.setTimestamp(15, now.timestamp()); statement.setTimestamp(16, now.timestamp()); statement.executeUpdate() }; return get(connection, id)!! }
    private fun updateRow(connection: Connection, id: String, input: PriceInput, actorId: String, version: Long, now: Instant): Price { connection.prepareStatement("UPDATE prices SET product_id=?,variant_id=?,seller_id=?,currency=?,region=?,customer_segment=?,base_minor=?,sale_minor=?,tax_rate_bps=?,effective_from=?,effective_to=?,version=?,created_by=?,updated_at=? WHERE id=?").use { statement -> statement.setString(1, input.productId); statement.setString(2, input.variantId); statement.setString(3, input.sellerId); statement.setString(4, input.currency); statement.setString(5, input.region); statement.setString(6, input.customerSegment); statement.setLong(7, input.baseMinor); if (input.saleMinor == null) statement.setNull(8, java.sql.Types.BIGINT) else statement.setLong(8, input.saleMinor); statement.setInt(9, input.taxRateBps); statement.setTimestamp(10, input.effectiveFrom.timestamp()); statement.setTimestamp(11, input.effectiveTo?.timestamp()); statement.setLong(12, version); statement.setString(13, actorId); statement.setTimestamp(14, now.timestamp()); statement.setString(15, id); statement.executeUpdate() }; return get(connection, id)!! }
    private fun snapshot(connection: Connection, price: Price, actorId: String, now: Instant) = connection.prepareStatement("INSERT INTO price_versions (id,price_id,version,snapshot_json,changed_by,changed_at) VALUES (?, ?, ?, ?::jsonb, ?, ?)").use { statement -> statement.setString(1, CommerceId.new("pver").value); statement.setString(2, price.id); statement.setLong(3, price.version); statement.setString(4, json.encodeToString(price)); statement.setString(5, actorId); statement.setTimestamp(6, now.timestamp()); statement.executeUpdate() }
    private fun outbox(connection: Connection, price: Price, type: String, correlationId: String, now: Instant) = connection.prepareStatement("INSERT INTO pricing_outbox_events (id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json) VALUES (?,?,?,?,1,?,?,?::jsonb)").use { statement -> statement.setString(1, newOutboxId()); statement.setString(2, "Price"); statement.setString(3, price.id); statement.setString(4, type); statement.setTimestamp(5, now.timestamp()); statement.setString(6, correlationId); statement.setString(7, json.encodeToString(PriceEventPayload(price.id, price.productId, price.variantId, price.currency, price.version, price.unitMinor, price.taxRateBps))); statement.executeUpdate() }
    private fun get(connection: Connection, id: String): Price? = connection.prepareStatement("SELECT * FROM prices WHERE id=?").use { statement -> statement.setString(1, id); statement.executeQuery().use { result -> if (result.next()) result.price() else null } }
    override fun unpublished(limit: Int): List<ServiceOutboxRecord> = withConnection { connection -> connection.prepareStatement("SELECT id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json::text FROM pricing_outbox_events WHERE published_at IS NULL ORDER BY occurred_at LIMIT ?").use { statement -> statement.setInt(1, limit); statement.executeQuery().use { result -> buildList { while (result.next()) add(ServiceOutboxRecord(result.getString(1), result.getString(2), result.getString(3), result.getString(4), result.getInt(5), result.getTimestamp(6).toInstant(), result.getString(7), result.getString(8))) } } } }
    override fun markPublished(ids: List<String>, publishedAt: Instant) { transaction { connection -> connection.prepareStatement("UPDATE pricing_outbox_events SET published_at=? WHERE id=ANY(?)").use { statement -> statement.setTimestamp(1, publishedAt.timestamp()); statement.setArray(2, connection.createArrayOf("varchar", ids.toTypedArray())); statement.executeUpdate() } } }
    private fun <T> withConnection(block: (Connection) -> T): T = dataSource.connection.use(block)
    private fun <T> transaction(block: (Connection) -> T): T = dataSource.connection.use { connection -> connection.autoCommit = false; try { block(connection).also { connection.commit() } } catch (error: Throwable) { connection.rollback(); throw error } }
}

private fun ResultSet.price(): Price = Price(getString("id"), getString("product_id"), getString("variant_id"), getString("seller_id"), getString("currency"), getString("region"), getString("customer_segment"), getLong("base_minor"), getLong("sale_minor").takeUnless { wasNull() }, getInt("tax_rate_bps"), getTimestamp("effective_from").toInstant().toString(), getTimestamp("effective_to")?.toInstant()?.toString(), getLong("version"), getString("created_by"), getTimestamp("created_at").toInstant().toString(), getTimestamp("updated_at").toInstant().toString())
private fun Instant.timestamp(): Timestamp = Timestamp.from(this)
