package com.ecommerce.seller

import com.ecommerce.platform.common.CommerceId
import com.ecommerce.platform.error.ApiException
import com.ecommerce.platform.error.ErrorCode
import com.ecommerce.platform.kafka.EventEnvelope
import com.ecommerce.platform.service.ServiceOutboxRecord
import com.ecommerce.platform.service.ServiceOutboxStore
import com.ecommerce.platform.service.newOutboxId
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.longOrNull
import java.sql.Connection
import java.sql.Timestamp
import java.time.Instant
import javax.sql.DataSource

class SellerRepository(private val ds:DataSource,private val json:Json):ServiceOutboxStore {
    fun apply(event:EventEnvelope)=tx{c->val fresh=c.prepareStatement("INSERT INTO seller_inbox_events(event_id,event_type) VALUES (?,?) ON CONFLICT DO NOTHING").use{s->s.setString(1,event.eventId);s.setString(2,event.eventType);s.executeUpdate()>0};if(!fresh)return@tx;val node=runCatching{json.parseToJsonElement(event.payloadJson).jsonObject}.getOrNull()?:return@tx;val orderId=node["id"]?.jsonPrimitive?.contentOrNull?:node["orderId"]?.jsonPrimitive?.contentOrNull?:event.aggregateId;val status=node["status"]?.jsonPrimitive?.contentOrNull;val items=node["items"] as? kotlinx.serialization.json.JsonArray ?: return@tx;items.forEach{item->val o=item as? JsonObject ?: return@forEach;val seller=o["sellerId"]?.jsonPrimitive?.contentOrNull?:return@forEach;val product=o["productId"]?.jsonPrimitive?.contentOrNull?:return@forEach;val variant=o["variantId"]?.jsonPrimitive?.contentOrNull?:return@forEach;c.prepareStatement("INSERT INTO seller_order_items(event_id,order_id,seller_id,product_id,variant_id,quantity,line_total_minor,currency,order_status,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING").use{s->s.setString(1,event.eventId);s.setString(2,orderId);s.setString(3,seller);s.setString(4,product);s.setString(5,variant);s.setInt(6,o["quantity"]?.jsonPrimitive?.intOrNull?:0);s.setLong(7,o["lineTotalMinor"]?.jsonPrimitive?.longOrNull?:0);s.setString(8,o["currency"]?.jsonPrimitive?.content?:"INR");s.setString(9,status);s.setTimestamp(10,Timestamp.from(Instant.parse(event.occurredAt)));s.executeUpdate()}}}
    fun create(owner:String,request:SellerApplication,actor:String,correlation:String):SellerResponse=tx{c->val id=CommerceId.new("sel").value;val now=Instant.now();c.prepareStatement("INSERT INTO sellers(id,owner_user_id,display_name,legal_name,email,phone,status) VALUES (?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,owner);s.setString(3,request.displayName.trim());s.setString(4,request.legalName.trim());s.setString(5,request.email.trim().lowercase());s.setString(6,request.phone);s.setString(7,SellerStatus.PENDING.name);s.executeUpdate()};c.prepareStatement("INSERT INTO seller_users(seller_id,user_id,role) VALUES (?,?,?)").use{s->s.setString(1,id);s.setString(2,owner);s.setString(3,"OWNER");s.executeUpdate()};c.prepareStatement("INSERT INTO seller_verification(seller_id,state) VALUES (?,?)").use{s->s.setString(1,id);s.setString(2,"PENDING");s.executeUpdate()};val response=get(c,id)!!;outbox(c,id,"SellerCreated",correlation,response);response}
    fun byUser(user:String):SellerResponse?=ds.connection.use{c->c.prepareStatement("SELECT s.* FROM sellers s JOIN seller_users u ON u.seller_id=s.id WHERE u.user_id=? ORDER BY s.created_at LIMIT 1").use{s->s.setString(1,user);s.executeQuery().use{if(it.next())it.seller()else null}}}
    fun get(id:String):SellerResponse?=ds.connection.use{c->get(c,id)}
    fun list(status:SellerStatus?,limit:Int):List<SellerResponse> = ds.connection.use{c->
        val sql = if(status==null) "SELECT * FROM sellers ORDER BY created_at DESC LIMIT ?" else "SELECT * FROM sellers WHERE status=? ORDER BY created_at DESC LIMIT ?"
        c.prepareStatement(sql).use{s->
            var i=1
            if(status!=null) s.setString(i++,status.name)
            s.setInt(i,limit.coerceIn(1,200))
            s.executeQuery().use{r->buildList{while(r.next())add(r.seller())}}
        }
    }
    fun update(user:String,request:SellerProfileUpdate):SellerResponse=tx{c->val current=byUser(c,user)?:throw ApiException(ErrorCode.NOT_FOUND,"Seller profile not found.",404);if(current.version!=request.version)throw ApiException(ErrorCode.CONFLICT,"Seller profile changed; reload and retry.",409);c.prepareStatement("UPDATE sellers SET display_name=?,legal_name=?,phone=?,version=version+1,updated_at=now() WHERE id=? AND version=?").use{s->s.setString(1,request.displayName.trim());s.setString(2,request.legalName.trim());s.setString(3,request.phone);s.setString(4,current.id);s.setLong(5,request.version);s.executeUpdate()};val result=get(c,current.id)!!;outbox(c,current.id,"SellerUpdated",current.id,result);result}
    fun transition(id:String,target:SellerStatus,actor:String,reason:String?,correlation:String):SellerResponse=tx{c->val current=get(c,id)?:throw ApiException(ErrorCode.NOT_FOUND,"Seller not found.",404);if(current.status==target)return@tx current;if(!valid(current.status,target))throw ApiException(ErrorCode.CONFLICT,"Invalid seller lifecycle transition.",409);c.prepareStatement("UPDATE sellers SET status=?,version=version+1,updated_at=now() WHERE id=?").use{s->s.setString(1,target.name);s.setString(2,id);s.executeUpdate()};c.prepareStatement("UPDATE seller_verification SET state=?,reviewed_by=?,reviewed_at=now() WHERE seller_id=?").use{s->s.setString(1,target.name);s.setString(2,actor);s.setString(3,id);s.executeUpdate()};val result=get(c,id)!!;outbox(c,id,"Seller${target.name.replaceFirstChar{it.uppercase()}}",correlation,result);result}
    fun orders(seller:String,limit:Int):List<SellerOrderItem > =ds.connection.use{c->c.prepareStatement("SELECT order_id,product_id,variant_id,quantity,line_total_minor,currency,order_status,occurred_at FROM seller_order_items WHERE seller_id=? ORDER BY occurred_at DESC LIMIT ?").use{s->s.setString(1,seller);s.setInt(2,limit.coerceIn(1,100));s.executeQuery().use{r->buildList{while(r.next())add(SellerOrderItem(r.getString(1),r.getString(2),r.getString(3),r.getInt(4),r.getLong(5),r.getString(6),r.getString(7),r.getTimestamp(8).toInstant().toString()))}}}}
    fun ledger(seller:String):List<LedgerEntry > =ds.connection.use{c->c.prepareStatement("SELECT id,entry_type,reference_id,amount_minor,currency,description,created_at FROM seller_ledger WHERE seller_id=? ORDER BY created_at DESC LIMIT 100").use{s->s.setString(1,seller);s.executeQuery().use{r->buildList{while(r.next())add(LedgerEntry(r.getString(1),LedgerEntryType.valueOf(r.getString(2)),r.getString(3),r.getLong(4),r.getString(5),r.getString(6),r.getTimestamp(7).toInstant().toString()))}}}}
    fun addLedger(seller:String,request:LedgerEntryRequest,actor:String):LedgerEntry=tx{c->if(request.referenceId.isBlank()||request.currency.length!=3)throw ApiException(ErrorCode.VALIDATION_ERROR,"Ledger entry is invalid.",400);val id=CommerceId.new("sleg").value;c.prepareStatement("INSERT INTO seller_ledger(id,seller_id,entry_type,reference_id,amount_minor,currency,description) VALUES (?,?,?,?,?,?,?) ON CONFLICT DO NOTHING").use{s->s.setString(1,id);s.setString(2,seller);s.setString(3,request.entryType.name);s.setString(4,request.referenceId);s.setLong(5,request.amountMinor);s.setString(6,request.currency.uppercase());s.setString(7,request.description?.take(500));s.executeUpdate()};c.prepareStatement("SELECT id,entry_type,reference_id,amount_minor,currency,description,created_at FROM seller_ledger WHERE seller_id=? AND entry_type=? AND reference_id=?").use{s->s.setString(1,seller);s.setString(2,request.entryType.name);s.setString(3,request.referenceId);s.executeQuery().use{r->r.next();LedgerEntry(r.getString(1),request.entryType,r.getString(3),r.getLong(4),r.getString(5),r.getString(6),r.getTimestamp(7).toInstant().toString())}}}
    fun deadLetter(event:EventEnvelope?,error:Throwable) { ds.connection.use{c->c.prepareStatement("INSERT INTO seller_dlq(event_id,event_type,aggregate_id,payload_json,error_message) VALUES (?,?,?,?,?) ON CONFLICT DO NOTHING").use{s->s.setString(1,event?.eventId);s.setString(2,event?.eventType);s.setString(3,event?.aggregateId);s.setString(4,event?.payloadJson?.let{runCatching{json.parseToJsonElement(it).toString()}.getOrNull()});s.setString(5,error.message?.take(2000)?:error::class.simpleName?:("unknown error"));s.executeUpdate()}} }
    override fun unpublished(limit:Int):List<ServiceOutboxRecord > =ds.connection.use{c->c.prepareStatement("SELECT id,aggregate_type,aggregate_id,event_type,schema_version,occurred_at,correlation_id,payload_json::text FROM seller_outbox_events WHERE published_at IS NULL ORDER BY occurred_at LIMIT ?").use{s->s.setInt(1,limit);s.executeQuery().use{r->buildList{while(r.next())add(ServiceOutboxRecord(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getInt(5),r.getTimestamp(6).toInstant(),r.getString(7),r.getString(8)))}}}}
    override fun markPublished(ids:List<String>,publishedAt:Instant){if(ids.isEmpty())return;ds.connection.use{c->c.prepareStatement("UPDATE seller_outbox_events SET published_at=? WHERE id=ANY(?)").use{s->s.setTimestamp(1,Timestamp.from(publishedAt));s.setArray(2,c.createArrayOf("varchar",ids.toTypedArray()));s.executeUpdate()}}}
    private fun outbox(c:Connection,aggregate:String,type:String,correlation:String,response:SellerResponse){c.prepareStatement("INSERT INTO seller_outbox_events(id,aggregate_type,aggregate_id,event_type,occurred_at,correlation_id,payload_json) VALUES (?,?,?,?,?,?,?::jsonb)").use{s->s.setString(1,newOutboxId());s.setString(2,"Seller");s.setString(3,aggregate);s.setString(4,type);s.setTimestamp(5,Timestamp.from(Instant.now()));s.setString(6,correlation);s.setString(7,json.encodeToString(response));s.executeUpdate()}}
    private fun get(c:Connection,id:String):SellerResponse?=c.prepareStatement("SELECT * FROM sellers WHERE id=?").use{s->s.setString(1,id);s.executeQuery().use{if(it.next())it.seller()else null}}
    private fun byUser(c:Connection,user:String):SellerResponse?=c.prepareStatement("SELECT s.* FROM sellers s JOIN seller_users u ON u.seller_id=s.id WHERE u.user_id=? ORDER BY s.created_at LIMIT 1").use{s->s.setString(1,user);s.executeQuery().use{if(it.next())it.seller()else null}}
    private fun java.sql.ResultSet.seller()=SellerResponse(getString("id"),getString("owner_user_id"),getString("display_name"),getString("legal_name"),getString("email"),getString("phone"),SellerStatus.valueOf(getString("status")),getLong("version"),getTimestamp("created_at").toInstant().toString(),getTimestamp("updated_at").toInstant().toString())
    private fun valid(from:SellerStatus,to:SellerStatus)=isValidSellerTransition(from,to)
    private fun <T>tx(b:(Connection)->T):T=ds.connection.use{c->c.autoCommit=false;try{b(c).also{c.commit()}}catch(e:Throwable){c.rollback();throw e}}
}
